// Click&Clean for Microsoft Edge - HOTCLEANER.COM - Copyright (c) 2020 Vlad & Serge Strukoff. All Rights Reserved.
// Minified by Google Closure Compiler 20190929.0.0
'use strict';(function(){const a=self.window,l=a.document,O=a.Date,D=a.String,p=a.Object,m=a.chrome,g=m.runtime,P=g.getURL,E=g.sendMessage;var q=Array.prototype;const n=Storage.prototype,F=Navigator.prototype,Q=XMLHttpRequest.prototype,G=DocumentFragment.prototype,b=Document.prototype,H=DOMImplementation.prototype,k=EventTarget.prototype,w=Event.prototype,h=Node.prototype,c=Element.prototype,r=HTMLElement.prototype,I=D.prototype.charCodeAt,t=q.push,R=q.join,S=b.createElement,J=k.addEventListener,T=k.removeEventListener,
U=k.dispatchEvent,V=c.hasAttribute,u=c.setAttribute,W=h.appendChild,K=b.querySelector,L=(q=p.getOwnPropertyDescriptor(b,"body"))&&q.get||null,x=a.JSON.stringify,X=a.JSON.parse,M=D.fromCharCode,N=O.now,Y=a.CustomEvent;try{var v=p.getOwnPropertyDescriptor(Function.prototype,"call");v&&(v.configurable=!1,v.writable=!1,p.defineProperty(Function.prototype,"call",v))}catch(f){}try{n.getItem=n.setItem=n.removeItem=n.clear=n.key=G.querySelector=G.querySelectorAll=b.adoptNode=b.getElementById=b.getElementsByClassName=
b.getElementsByName=b.getElementsByTagName=b.getElementsByTagNameNS=b.createDocumentFragment=b.createTextNode=b.createElement=b.createElementNS=b.evaluate=b.createEvent=b.createCDATASection=b.execCommand=b.querySelector=b.querySelectorAll=b.open=b.write=b.writeln=b.prepend=b.importNode=b.registerElement=H.createHTMLDocument=H.createDocument=k.addEventListener=k.removeEventListener=k.dispatchEvent=w.preventDefault=w.stopPropagation=w.stopImmediatePropagation=h.appendChild=h.cloneNode=h.getRootNode=
h.insertBefore=h.removeChild=h.replaceChild=c.attachShadow=c.createShadowRoot=c.getElementsByClassName=c.getElementsByTagName=c.getElementsByTagNameNS=c.append=c.remove=c.before=c.after=c.prepend=c.querySelector=c.querySelectorAll=c.requestPointerLock=c.setAttribute=c.removeAttribute=c.removeAttributeNS=c.removeAttributeNode=c.replaceWith=c.insertAdjacentElement=c.insertAdjacentText=c.insertAdjacentHTML=r.focus=r.click=F.sendBeacon=Q.open=function(){}}catch(f){}delete a.AnimationWorklet;delete a.AudioContext;
delete a.Blob;delete a.CSS;delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;delete a.DOMParser;delete a.Event;delete a.FormData;delete a.Image;delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;delete a.Navigator;delete a.PaintWorklet;delete a.Proxy;delete a.Range;delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;delete a.XMLHttpRequestUpload;
delete a.XMLSerializer;delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.console;delete a.open;delete a.alert;delete a.confirm;delete a.eval;delete a.localStorage;delete a.postMessage;delete a.prompt;delete a.stop;delete a.customElements;delete a.navigator;delete h.textContent;delete b.cookie;delete b.body;delete F.serviceWorker;delete c.innerHTML;delete c.outerHTML;delete r.innerText;delete r.outerText;delete m.Event;for(var y in m)if("runtime"==y)for(var z in g)"function"===typeof g[z]&&
"connect"!==z&&(g[z]=()=>{});else if("object"===typeof m[y])try{p.defineProperty(m,y,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(f){}const A=(a,e)=>{E.call(g,x(a),e||function(){})},B=(a,e)=>{var b=e.g?e.g:"frm";if(!V.call(L.call(l),b)){var f=K.call(l,e.a);f&&0<f.offsetHeight&&f.classList.add(e.b);if(f=K.call(l,e.c)){u.call(L.call(l),b,"");var d=S.call(l,"iframe"),c=()=>{T.call(d,"load",c,!1);d.style.setProperty("display","none");d.style.setProperty("display","block")};e.d?u.call(d,
e.d,e.e):d.className=e.e;e.f&&(d.id=e.f);u.call(d,"scrolling","no");u.call(d,"frameborder","0");d.style.setProperty("float","none");d.src=P.call(g,a);J.call(d,"load",c,!1);W.call(f,d)}}},C=(f,e)=>{var b=[],c=[3,0,0,-3];e=x({t:N(),i:f,v:e});for(var d=0,g=e.length;d<g;d++)f=c[d%4],d+f<g?t.call(b,I.call(e,d+f)):t.call(b,I.call(e,d));U.call(a,new Y("mxcse",{detail:b}))},Z=a=>{for(var b=[],c=[3,0,0,-3],f,d=0,g=a.length;d<g;d++)f=c[d%4],d+f<g?t.call(b,M(a[d+f])):t.call(b,M(a[d]));return R.call(b,"")};J.call(a,
"message",a=>{if("https://www.hotcleaner.com"===(a.origin||"")&&a.data.constructor===Array){try{var b=X(Z(a.data))}catch(aa){b={}}1E3>N()-b.t&&(a=b.i,1E3>a&&(2==a?A({id:102,url:b.u,incognito:b.p},null):30==a?A({id:130,a:b.a},function(a){C(130,a)}):699<a&&712>a?E.call(g,x({id:700,v:a})):200==a?B("history4788.html",b):201==a?B("cache4788.html",b):202==a?B("cookies4788.html",b):203==a&&A({id:15,v:"000E"},a=>{200==a.code&&a.data&&C(70,a.data)})))}},!0);C(1,9700)})();