// Click&Clean for Microsoft Edge - HOTCLEANER.COM - Copyright (c) 2020 Vlad & Serge Strukoff. All Rights Reserved.
// Minified by Google Closure Compiler 20190929.0.0
'use strict';(function(){const a=self,q=a.document;var g=a.navigator;const W=a.Audio;var v=a.String;const r=a.Object,X=a.Image,ia=g.platform,Y=a.CustomElementRegistry?!0:!1,G=g.appVersion||g.userAgent||"",K=/Edg/.test(G),L=/OPR/.test(G);g=a.chrome;const m=g.runtime,H=g.i18n,p=g.tabs,M=g.windows,ja=m.getURL,n=m.sendMessage,Z=M.create,aa=p.query,ka=p.reload,ba=p.remove,la=p.update,N=H.getMessage,ca=Navigator.prototype,O=DocumentFragment.prototype,c=Document.prototype,da=DOMImplementation.prototype,C=EventTarget.prototype,
P=Event.prototype,k=Node.prototype,e=Element.prototype,w=HTMLElement.prototype,ea=HTMLMediaElement.prototype,ma=O.querySelector,y=c.createElement,fa=c.createDocumentFragment,na=c.querySelector,Q=C.addEventListener,t=k.appendChild,oa=k.removeChild,R=k.insertBefore,pa=v.prototype.charAt,S=e.attachShadow||null,qa=ea.play,l=a.JSON.stringify,T=a.parseInt,I=a.close,D=a.setTimeout,E=(v=r.getOwnPropertyDescriptor(k,"textContent"))&&v.set||null,ha=(v=r.getOwnPropertyDescriptor(c,"body"))&&v.get||null;try{var u=
r.getOwnPropertyDescriptor(Function.prototype,"call");u&&(u.configurable=!1,u.writable=!1,r.defineProperty(Function.prototype,"call",u))}catch(z){}try{O.querySelector=O.querySelectorAll=c.adoptNode=c.append=c.captureEvents=c.getElementById=c.getElementsByClassName=c.getElementsByName=c.getElementsByTagName=c.getElementsByTagNameNS=c.createDocumentFragment=c.createTextNode=c.createElement=c.createElementNS=c.evaluate=c.createEvent=c.createCDATASection=c.execCommand=c.querySelector=c.querySelectorAll=
c.open=c.write=c.writeln=c.prepend=c.importNode=c.registerElement=da.createHTMLDocument=da.createDocument=C.addEventListener=C.removeEventListener=C.dispatchEvent=P.preventDefault=P.stopPropagation=P.stopImmediatePropagation=k.appendChild=k.cloneNode=k.getRootNode=k.insertBefore=k.removeChild=k.replaceChild=e.attachShadow=e.createShadowRoot=e.getElementsByClassName=e.getElementsByTagName=e.getElementsByTagNameNS=e.append=e.remove=e.before=e.after=e.prepend=e.querySelector=e.querySelectorAll=e.requestPointerLock=
e.setAttribute=e.removeAttribute=e.removeAttributeNS=e.removeAttributeNode=e.replaceWith=e.insertAdjacentElement=e.insertAdjacentText=e.insertAdjacentHTML=w.focus=w.click=ca.sendBeacon=ea.play=()=>{}}catch(z){}delete a.AnimationWorklet;delete a.Audio;delete a.AudioContext;delete a.Blob;delete a.CSS;delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;delete a.DOMParser;delete a.Event;delete a.FormData;delete a.Image;delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;
delete a.Navigator;delete a.PaintWorklet;delete a.Proxy;delete a.Range;delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;delete a.XMLHttpRequestUpload;delete a.XMLSerializer;delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.console;delete a.open;delete a.alert;delete a.confirm;delete a.eval;delete a.localStorage;delete a.postMessage;delete a.prompt;
delete a.stop;delete a.navigator;delete k.textContent;delete c.cookie;delete c.body;delete ca.serviceWorker;delete e.innerHTML;delete e.outerHTML;delete w.innerText;delete w.outerText;delete g.Event;for(var U in g)if("runtime"==U)for(var V in m)"function"===typeof m[V]&&"connect"!==V&&(m[V]=()=>{});else if("object"===typeof g[U])try{r.defineProperty(g,U,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(z){}var J;const ra=()=>{var c,e,g=!1,h=/Comodo/.test(G)?"dragon://":/OPR/.test(G)?"opera://":
"chrome://",k="menu0";n.call(m,l({id:3}),a=>{const b=b=>{var a=y.call(q,"div");a.className=0==b?"nav act":"nav";a.id="menu"+b;E.call(a,A[b]);Q.call(a,"click",v,!1);return a};c=a;var A=N.call(H,"menu").split(";");a=fa.call(q);var d=y.call(q,"div"),x=y.call(q,"div"),f=y.call(q,"div");d.id="panel";x.id="menu";x.className="w102";f.id="box";701===c.ui?f.style.setProperty("filter","sepia(.5)"):702===c.ui?f.style.setProperty("filter","grayscale(1) brightness(1.17)"):703===c.ui?f.style.setProperty("filter",
"invert(1) sepia(1) saturate(0) brightness(1.7) contrast(.8)"):704===c.ui?f.style.setProperty("filter","invert(.9) sepia(1) brightness(.85) hue-rotate(20deg)"):705===c.ui?f.style.setProperty("filter","invert(.9) sepia(1) brightness(0.95) hue-rotate(155deg)"):706===c.ui&&f.style.setProperty("filter","invert(.87) sepia(1) brightness(0.95) hue-rotate(0deg)");t.call(d,x);t.call(d,f);t.call(a,d);t.call(x,b(0));t.call(x,b(1));t.call(x,b(3));r(k,f);t.call(J,a);Q.call(f,"click",C,!1);D(()=>{d.className="w310"},
10);/Win/.test(ia)&&"ghgabhipcejejjmhhchfonmamedcbeod"==m.id&&n.call(m,l({id:15,v:"000E"}),a=>{a&&a.data&&(e=a.data,x.className="w77",R.call(x,b(2),B("#menu3")),D(()=>{B("#i9").firstElementChild.src="img4788/menu/quickscan.png";B("#i14").firstElementChild.src="img4788/menu/cleanup.png";var a=N.call(H,"menu0").split(";");E.call(B("#i9").firstElementChild.nextElementSibling,a[8]);E.call(B("#i14").firstElementChild.nextElementSibling,a[12])},1))})});const v=a=>{var b=a.target.id;k!=b&&(k&&(B("#"+k).className=
"nav"),k=b,a.target.className="nav act",r(b))},r=(c,b)=>{b=b||B("#box");if("menu0"==c)var A=[3,"red","close.png",0,7,0,"options1.png",18,3,"magenta","clear.png",1,7,0,"options1.png",18,7,0,"tabs1.png",2,3,"violet","cache.png",3,7,0,"trash1.png",4,3,"violet","history.png",5,7,0,"trash1.png",6,0,"blue","quickscan.png",7,3,"violet","downloads.png",9,7,0,"trash1.png",10,0,"choko","cookie.png",15,7,0,"trash1.png",16,0,"seawave",e?"cleanup.png":"memory.png",e?12:13,3,"violet","security.png",14,0,"carbon",
"incognito.png",11,0,"teal","report.png",17,0,"magenta","options.png",18,7,0,"themes.png",19,0,"green","updates.png",20,0,"yellow","rate32.png",21];else"menu1"==c?A=[3,"seawave","plugins.png",0,3,"green","extensions.png",1,3,"orange","experiments.png",2,3,"magenta","internals.png",3,0,"violet","dns.png",4,3,"violet","history.png",5,0,"violet","cache.png",6,0,"red","key.png",7,3,"blue","version.png",8,7,0,"arrow1.png",9,0,"red","conflicts.png",10,0,"teal","policies.png",11,0,"blue","releases.png",
12,7,0,"calendar1.png",13,0,"blue","credits.png",14,0,"teal","bug.png",15]:"menu2"==c?A=[3,"green","winsec.png",0,3,"blue","info.png",1,3,"red","uninstall.png",2,3,"violet","defragmenter.png",3,3,"magenta","sound.png",4,3,"marine","network.png",5,7,0,"connect.png",6,7,0,"wireless.png",7,3,"teal","devices.png",8,3,"violet","display.png",9,3,"blue","services.png",10,3,"seawave","directx.png",11]:"menu3"==c&&(d(ja.call(m,"ctrb4788.html"),!1,!0,!1),I.call(a));if("menu3"!==c){var k=0;c=N.call(H,c).split(";");
for(var x=fa.call(q),f,g,h,n,l,p,r,u,v,w,z=0;z<A.length;z+=4)r=z/4,l=A[z],p=A[z+1],u=A[z+2],r="i"+r,u="img4788/menu/"+u,w=c[A[z+3]],7>l?(v=0,f=y.call(q,"div"),g=y.call(q,"div"),n=y.call(q,"div"),h=new X,p="btn "+p,2<l?(p+=" wide",f.className="btnBoxWide"):f.className="btnBox",g.id=r,g.className=p,h.className="icn",n.className="txt0",h.dataset.url=h.src=u,E.call(n,w),t.call(g,h),t.call(g,n),t.call(f,g),t.call(x,f)):(f=y.call(q,"div"),l=y.call(q,"div"),h=new X,h.src=u,f.id=r,f.className="adt a"+v,h.className=
"icnm",l.className="txt1",E.call(l,w),t.call(f,h),R.call(g,f,n),R.call(g,l,n),v++),k++;for(;b.firstElementChild;)oa.call(b,b.firstElementChild);t.call(b,x);b.style.display=""}},C=c=>{c=c.target.id?c.target:c.target.parentElement;if("menu0"==k){var b=T(c.id.slice(1));0==b?n.call(m,l({id:4})):1==b?(n.call(m,l({id:0,local:1,url:"cleaner4788.html",w:770,h:500})),I(a)):2==b?F(c):3==b?(n.call(m,l({id:0,local:1,url:"cleaner4788.html",w:770,h:500})),I(a)):4==b?u(0,0,0):5==b?d("https://www.hotcleaner.com/cache-viewer.html",
!1,!0,!1):6==b?F(c,"cache"):7==b?d("https://www.hotcleaner.com/clear-browsing-history.html",!1,!0,!1):8==b?F(c,"history"):9==b?d("https://www.hotcleaner.com/clickclean-scan-for-malware.html",!0,!0,!1):10==b?d(h+"downloads/",!1,!0,!1):11==b?F(c,"downloads",!1,!0,!1):12==b?d("https://www.hotcleaner.com/cookie-wiper.html",!1,!0,!1):13==b?F(c,"cookies"):14==b?e?w(115):d(h+"system/",!1,!0,!1):15==b?d("https://www.hotcleaner.com/clickclean-app.html#cevjhaa",!0,!0,!1):16==b?Z.call(M,{url:h+"newtab/",incognito:!0,
focused:!0,top:-3,left:-8,width:screen.availWidth+16,height:screen.availHeight+6}):17==b?d("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#cevjhaa",!0,!0,!1):18==b?(n.call(m,l({id:0,local:1,url:"cleaner4788.html",w:770,h:500})),I.call(a)):19==b?d("https://www.hotcleaner.com/clickclean-appearance.html",!1,!0,!1):20==b?d("https://www.hotcleaner.com/clickclean_chrome_update_checker.html#cevjhaa",!0,!0,!1):21==b&&d(K?"https://api64.com/edge-reviews":"https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews",
!1,!0,!1)}else"menu1"==k?(b=T(c.id.slice(1)),0==b?d(h+"components/",!1,!0,!1):1==b?d(h+"extensions/",!1,!0,!1):2==b?d(h+"flags/",!1,!0,!1):3==b?d(h+"net-export/",!1,!0,!1):4==b?d(h+"net-internals/#dns",!1,!0,!1):5==b?d("https://www.hotcleaner.com/clear-browsing-history.html",!1,!0,!1):6==b?d("https://www.hotcleaner.com/cache-viewer.html",!1,!0,!1):7==b?Z.call(M,{url:"pgen4788.html",type:"popup",focused:!0,width:350,height:216}):8==b?d(L?h+"about/":h+"version/",!1,!0,!1):9==b?d(K?"https://blogs.windows.com/msedgedev/":
L?"https://blogs.opera.com/desktop/":"https://blog.google/products/chrome/",!1,!0,!1):10==b?d(h+(e?"conflicts/":"crashes/"),!1,!0,!1):11==b?d(h+"policy/",!1,!0,!1):12==b?d(K?"https://www.microsoftedgeinsider.com/download":L?"https://help.opera.com/en/opera-version-history/":"https://chromereleases.googleblog.com/",!1,!0,!1):13==b?d("https://www.chromium.org/developers/calendar",!1,!0,!1):14==b?d("o"==pa.call(h,0)?h+"about/credits/":h+"credits/",!1,!0,!1):15==b&&d("https://code.google.com/p/chromium/issues/list",
!1,!0,!1)):"menu2"==k&&(b=T(c.id.slice(1))+100,w(b))},w=a=>{n.call(m,l({id:15,v:"00"+a.toString(16)}),()=>{})},u=(a,b,c)=>{aa.call(p,b?{active:!0}:{},d=>{d.forEach((e,f)=>{b?ka.call(p,e.id):f?ba.call(p,e.id):la.call(p,e.id,{url:a?"about:blank":"chrome-search://local-ntp/local-ntp.html"});c&&f==d.length-1&&D(c,500)})})},F=(a,b,c)=>{var d,e=b?a.previousElementSibling:a.firstElementChild;e.src="img4788/menu/wipe.gif";const f=()=>{if(d.p28&&W){var a=new W("img4788/erased.ogg");qa.call(a)}D(()=>{e.src=
"img4788/menu/done.png";D(()=>{e.src=e.dataset.url;c&&aa.call(p,{},a=>{a.forEach((a,b)=>{ba.call(p,a.id)})})},900);g=!1},300)};g||(g=!0,n.call(m,l({id:3}),a=>{d=a;b?(a={id:19,v:{since:-1},v2:{}},a.v2[b]=!0,n.call(m,l(a),f)):d.p0||c?u(c,0,()=>{n.call(m,l({id:18}),f)}):n.call(m,l({id:18}),()=>{d.p25?u(0,1,f):f()})}))},d=(a,b,c,d)=>{n.call(m,l({id:9,url:a,selected:c,first:d,incognito:b}))},B=a=>S&&Y?ma.call(J,a):na.call(q,a)};Q.call(a,"DOMContentLoaded",()=>{J=S&&Y?S.call(ha.call(q),{mode:"closed"}):
ha.call(q);var a=y.call(q,"link");a.rel="stylesheet";a.type="text/css";a.href="css4788/menu4788.css";t.call(J,a);D(ra,1)},!0)})();