// Click&Clean for Microsoft Edge - HOTCLEANER.COM - Copyright (c) 2020 Vlad & Serge Strukoff. All Rights Reserved.
// Minified by Google Closure Compiler 20190929.0.0
'use strict';(function(){function v(){var b=f("pass"),c=G.call(a,f("length").value),d=new Uint32Array(25);x.call(y,d);for(var g=0;g<d.length;g++)e+=H.call(d[g],36);var e=I.call(e,-c);d=new Uint8Array(1);var h="";for(g=0;g<e.length;g++)c=e.charAt(g),J(c)&&(x.call(y,d),128<d[0]&&(c=K.call(c))),h+=c;b.value=h;b.select()}function L(){var a=f("pass");a&&(M.call(z,N.call(A,{id:50,v:a.value})),a.focus())}function f(a){return O.call(P,a)}var a=self,P=a.document,A=a.JSON,y=a.crypto,h=a.Object,d=a.chrome,z=d.runtime,k=
d.windows,B=d.i18n,M=z.sendMessage,Q=k.getCurrent,R=k.update,S=B.getMessage,C=String.prototype,D=Navigator.prototype,T=XMLHttpRequest.prototype,E=DocumentFragment.prototype,b=Document.prototype,F=DOMImplementation.prototype,l=EventTarget.prototype,q=Event.prototype,e=Node.prototype,c=Element.prototype,m=HTMLElement.prototype,r=l.addEventListener,O=b.getElementById,x=Crypto.prototype.getRandomValues,H=Number.prototype.toString,I=C.slice,K=C.toUpperCase,N=A.stringify,G=a.parseInt,J=a.isNaN;try{var n=
h.getOwnPropertyDescriptor(Function.prototype,"call");n&&(n.configurable=!1,n.writable=!1,h.defineProperty(Function.prototype,"call",n))}catch(w){}var p=h.getOwnPropertyDescriptor(e,"textContent");try{E.querySelector=E.querySelectorAll=b.adoptNode=b.append=b.captureEvents=b.getElementById=b.getElementsByClassName=b.getElementsByName=b.getElementsByTagName=b.getElementsByTagNameNS=b.createDocumentFragment=b.createTextNode=b.createElement=b.createElementNS=b.evaluate=b.createEvent=b.createCDATASection=
b.execCommand=b.querySelector=b.querySelectorAll=b.open=b.write=b.writeln=b.prepend=b.importNode=b.registerElement=F.createHTMLDocument=F.createDocument=l.addEventListener=l.removeEventListener=l.dispatchEvent=q.preventDefault=q.stopPropagation=q.stopImmediatePropagation=e.appendChild=e.cloneNode=e.getRootNode=e.insertBefore=e.removeChild=e.replaceChild=c.attachShadow=c.createShadowRoot=c.getElementsByClassName=c.getElementsByTagName=c.getElementsByTagNameNS=c.append=c.remove=c.before=c.after=c.prepend=
c.querySelector=c.querySelectorAll=c.requestPointerLock=c.setAttribute=c.removeAttribute=c.removeAttributeNS=c.removeAttributeNode=c.replaceWith=c.insertAdjacentElement=c.insertAdjacentText=c.insertAdjacentHTML=m.focus=m.click=D.sendBeacon=T.open=function(){}}catch(w){}delete a.AnimationWorklet;delete a.Audio;delete a.AudioContext;delete a.Blob;delete a.CSS;delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;delete a.DOMParser;delete a.Event;delete a.FormData;delete a.Image;
delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;delete a.Navigator;delete a.PaintWorklet;delete a.Proxy;delete a.Range;delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;delete a.XMLHttpRequestUpload;delete a.XMLSerializer;delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.console;delete a.open;delete a.alert;delete a.confirm;delete a.eval;
delete a.localStorage;delete a.postMessage;delete a.prompt;delete a.stop;delete a.navigator;delete e.textContent;delete b.cookie;delete b.body;delete D.serviceWorker;delete c.innerHTML;delete c.outerHTML;delete m.innerText;delete m.outerText;delete d.Event;for(var t in d)if("runtime"==t)for(var u in d.runtime)"function"===typeof d.runtime[u]&&"connect"!==u&&(d.runtime[u]=function(){});else if("object"===typeof d[t])try{h.defineProperty(d,t,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(w){}r.call(a,
"DOMContentLoaded",function(){Q.call(k,function(b){var c=a.innerWidth,d,e;216>a.innerHeight&&(e=216+(a.outerHeight-a.innerHeight));350>c&&(d=350+(350-c));R.call(k,b.id,{width:d,height:e,focused:!0})});var b=S.call(B,"pgen").split(";");p.set.call(f("hdr"),b[0]);p.set.call(f("pan").firstElementChild.childNodes[0],b[1]);p.set.call(f("gen"),b[2]);p.set.call(f("copy"),b[3]);r.call(f("gen"),"click",v,!1);r.call(f("copy"),"click",L,!1);v()},!1)})();