((twod, k) => { if(window[k]) return; window[k] = true;(()=>{"use strict";function e(e,t){let n,o=!0;return"boolean"==typeof e?(o=e,n=t):n=e,bn((e=>{const t=Qt(_n.document);"interactive"==t||"complete"==t?(n&&n(),e()):wn.addEventListener("DOMContentLoaded",(()=>{n&&n(),e()}),Mt({capture:o,once:!0}))}))}const t=e=>{const t=Object.call,n=t.bind(t),o=Object.assign,s=Object.getOwnPropertyDescriptor,r=e=>o({__proto__:null},e);return r({sourceWindow:e,cSO:r,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,
A_sh:[].shift,A_j:[].join,A_f:[].filter,A_iO:[].indexOf,A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,O_dPy:Object.defineProperty,O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:s,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:Object.getPrototypeOf,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_i:MutationEvent.prototype.initMutationEvent,M_pA:MutationEvent.prototype.ADDITION,
M_pAT:MutationEvent.AT_TARGET,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,R_r:s(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,
S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,
X_pSU:XMLHttpRequest.prototype.UNSENT,X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,D_cS:s(Document.prototype,"currentScript").get,D_gRS:s(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_aN:s(MutationEvent.prototype,"attrName").get,M_rN:s(MutationEvent.prototype,"relatedNode").get,C_d:s(CustomEvent.prototype,"detail").get,
W_aEL:addEventListener,W_rEL:removeEventListener,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,MouseEvent,MutationEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,alert,prompt,confirm,close,
getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement})},n="vault"in twod;if(n&&void 0===twod.vault)throw"Invalid vault"
;const o=twod.vault=twod.vault||t(twod.unsafeWindow),{cSO:s,F_c:r,F_a:i,F_b:a,F_tS:c,A_fE:d,A_so:l,A_sh:u,A_j:p,A_f:m,A_iO:g,A_iA:f,O_a:_,O_k:v,O_v:h,O_dP:w,O_dPy:b,O_hOP:y,O_gOPN:M,O_gOPD:E,O_gOPDs:L,O_gPO:O,O_tS:S,J_p:x,J_s:I,M_f:R,M_r:j,M_m:D,M_i:C,M_pA:P,M_pAT:$,N_tS:A,N_MSI:T,P_t:U,P_c:N,R_rABS:B,R_rAT:F,R_r:X,R_enq:k,R_cl:q,S_fCC:W,S_sl:H,S_su:J,S_iO:G,S_sp_nr:K,S_tr:z,S_rA_nr:V,S_cCA:Y,S_tLC:Z,S_tUC:Q,Y_tST:ee,D_pFS:te,D_cS:ne,D_gRS:oe,D_cE:se,D_gEBT:re,E_r:ie,E_s:ae,M_aN:ce,M_rN:de,C_d:le,U_cOU:ue,U_rOU:pe,X_o:me,X_s:ge,X_pSD:fe,X_pSH:_e,X_pSL:ve,X_pSO:he,X_pSU:we,D_n:be,I_tS:ye,W_aEL:Me,W_rEL:Ee,parseInt:Le,parseFloat:Oe,console:Se,encodeURIComponent:xe,decodeURIComponent:Ie,encodeURI:Re,decodeURI:je,escape:De,unescape:Ce,atob:Pe,btoa:$e,postMessage:Ae,dispatchEvent:Te,alert:Ue,prompt:Ne,confirm:Be,close:Fe,getElementById:Xe,createEvent:ke,createElement:qe,CustomEvent:We,CompositionEvent:He,KeyboardEvent:Je,MouseEvent:Ge,MutationEvent:Ke,MutationObserver:ze,Uint8Array:Ve,FileReader:Ye,DOMParser:Ze,XMLHttpRequest:Qe,Function:et,RegExp:tt,Promise:nt,Blob:ot,ReadableStream:st,Number:rt,String:it,Proxy:at,Window:ct}=o,dt=r,lt=i,ut=v,pt=h,mt=_,gt=b,ft=M,_t=E,vt=O,ht=f,wt=j,bt=D,yt=(e,t,n)=>dt(lt,e,t,n),Mt=s,Et=(e,t,n)=>(gt(e,t,Mt({
value:n,configurable:!0,enumerable:!0,writable:!0})),e),Lt=(e,t)=>{const n=_t(e,t);return n?Mt(n).value:void 0},Ot=(e,t)=>{const n=(e,t,o)=>{const s=_t(e,t),r=s?Mt(s):void 0;let i;return r?r.enumerable?r.value:void 0:--o>=0&&(i=vt(e))?n(i,t,o):void 0};return n(e,t,5)},St=e=>{const t=(t,...n)=>yt(e,t,n);return Et(t,"wrappedJSObject",e),t},xt=()=>e=>St(e),It=St(a),Rt=x,jt=e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const i=typeof e;if("object"===i){if(n){
if(-1!=At(n,e))throw"Converting circular structure to JSON";Et(n,n.length,e)}else n=[e];if(ht(e)){let i="";for(let o=0;o<e.length;o++){let a;a=Ut(e,o)?Ut(s=e,r=o)?s[r]:void 0:Ot(e,o);const c=t(a,n);i+=`${o?",":""}${void 0===c?"null":c}`}o=`[${i}]`}else{let s="";Tt(ut(e),(o=>{const r=t(e[o],n);void 0!==r&&(s+=`${s?",":""}${I(o)}: ${r}`)})),o=`{${s}}`}n.length-=1}else{if("bigint"===i)throw"Do not know how to serialize a BigInt";o=I(e)}}var s,r;return o};return t(e)},Dt=(xt()(l),
xt()(u)),Ct=(xt()(m),(e,t,n)=>{const o=e.length;let s=t||0;if(s>=o)return[];s<0&&(s=bt(0,o+s));let r=void 0===n?o:n;r<0&&(r=bt(0,o+r)),r>o&&(r=o);const i=Mt({});for(let t=s;t<r;t++)i[t]=Lt(e,t);return pt(i)}),Pt=xt()(p),$t=(e,t)=>{let n=e.length||0;return Et(e,n,t),n++,e.length=n},At=xt()(g),Tt=xt()(d),Ut=xt()(y),Nt=xt()(K),Bt=xt()(H),Ft=St(S),Xt=vt({}),kt=e=>{const t=Mt(e),n=ft(t);for(let e=0;e<n.length;e++){const o=n[e],s=t[o];null!==s&&"object"==typeof s&&vt(s)===Xt&&(t[o]=kt(s))}return t
},qt=e=>{const t=Nt(Ft(e)," ");return Bt(Pt(Ct(t,1)," "),0,-1)},Wt=xt()(c),Ht=xt()(C),Jt=P,Gt=xt()(A),Kt=xt()(U),zt=(xt()(N),xt()(B),xt()(F),xt()(X),k&&xt()(k),q&&xt()(q),W),Vt=xt()(J),Yt=xt()(G),Zt=(xt()(z),xt()(V||function(e,t){return Pt(Nt(this,e),t)}),xt()(Y)),Qt=(xt()(Z),xt()(Q),St(te),St(ne),St(oe)),en=St(se),tn=St(re),nn=(St(ie),St(ae),St(ce)),on=St(de),sn=St(le),rn=pe,an=(xt()(me),xt()(ge),be),cn=We,dn=ze,ln=ot,un=function(e,t){return Lt(e,t)},pn=Mt({addEventListener:!1,Array:!0,Blob:!0,
close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,MutationEvent:!0,Number:!0,Object:!0,Promise:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),mn=(()=>{const e=Mt({getElementById:Xe,createEvent:ke,createElement:qe,dispatchEvent:Te,addEventListener,removeEventListener}),t=Mt({});return Tt(ut(e),(n=>{try{const o=e[n];t[n]=function(...e){return yt(o,_n.document,e)}}catch(e){t[n]=((e,t)=>{
if(hn.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}})(e,`document.${n}`)}})),t})(),gn=Mt({top:!0,location:!0}),fn=twod,{unsafeWindow:_n,unsafeThis:vn}=fn;twod.bridges=twod.bridges||Mt({});const hn=twod.console=twod.console||Mt({}),wn=Mt({addEventListener:It(Me,_n),removeEventListener:It(Ee,_n)});Tt(ut(gn),(async e=>{if(!wn[e])try{const t=_n[e];if(null==t)return;wn[e]=t}catch(e){}})),Tt(ut(pn),(async e=>{
if(!wn[e])try{let t=Lt(_n,e);if(void 0===t&&(vn===_n||void 0===(t=Lt(vn,e))))return;const n=pn[e];wn[e]=!1===n&&"function"==typeof t?It(t,vn):t}catch(e){}}));const bn=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],Tt(t,(t=>t(e)))}else t=e;o=!0}}));const s=Mt({then:e=>(o?e(t):$t(n,e),s)});return s},yn=()=>Gt(an()+19831206*wt()+1,36),Mn=(()=>{const{console:e,bridges:t}=twod,n=Mt({});let o;const s=(e,t)=>{let o=[],s=[];const r=()=>{o=[],s=[],i=null,delete n[e]};let i=Mt({
postMessage:n=>{t.send("port.message",Mt({response_id:e,value:n}))},onMessage:Mt({addListener:e=>{$t(o,e)}}),onDisconnect:Mt({addListener:e=>{$t(s,e)}}),disconnect:()=>{t.send("port.message",Mt({response_id:e,disconnect:!0})),r()}});return n[e]=Mt({message:e=>{o&&Tt(o,(t=>t(e)))},disconnect:()=>{s&&Tt(s,(e=>e())),r()}}),i};return Mt({message:(t,r)=>{let i;if(t.connect){if(!t.destination||!t.response_id)throw"invalid message";o&&o(t.destination,s(t.response_id,r))}else{
if(!t.response_id)throw"invalid message";if(!(i=n[t.response_id]))return void e.warn("ports: unkown id",t.response_id,t);t.disconnect?i.disconnect():i.message(t.value)}},connect:e=>{const n=yn();return t.first.send("port.message",Mt({response_id:n,connect:!0,destination:e})),s(n,t.first)},onConnect:Mt({addListener:e=>{o=e}})})
})(),{setInterval:En,setTimeout:Ln,clearInterval:On,clearTimeout:Sn,console:xn,cloneInto:In,exportFunction:Rn,createObjectIn:jn}=_n,Dn=Object.assign({},xn),Cn=En.bind(_n),Pn=Ln.bind(_n),$n=On.bind(_n),An=(Sn.bind(_n),vn==_n.top),{arrayBuffer:Tn,blob:Un}=_n.Response.prototype,{arrayBuffer:Nn}=_n.Blob.prototype,{then:Bn}=_n.Promise.prototype,{fetch:Fn,location:Xn,document:kn,Response:qn}=_n,Wn=St(Tn),Hn=St(Un),Jn=St(Nn),Gn=In,Kn=(e,t)=>{const n=en(_n.document,"http://www.w3.org/1999/xhtml",e)
;return"string"==typeof t?n.append(t):t&&Tt(ut(t),(e=>{"textContent"==e?n.textContent=t[e]:n.setAttribute(e,t[e])})),n},zn=t=>{const n=_n.document;if(n.body||"text/xml"==n.contentType)t();else{let n=!1;const o=()=>{n=!0,zn(t)},s=Mt({capture:!0,once:!0});wn.addEventListener("DOMNodeInserted",o,s),e((()=>{n||(wn.removeEventListener("DOMNodeInserted",o,s),t())}))}},Vn=t=>{e((()=>{Pn((()=>t()),1)}))};let Yn,Zn;const Qn=Xn.host,eo=e=>{"n:"==Vt(e,0,2)?Yn=Vt(e,2):e&&(Zn=Vt(e,2))
},to=()=>Yn||(Zn?((e,t)=>{let n=0;if(0===e.length)return"00";const o=e+t;for(let e=0;e<o.length;e++)n=(n<<5)-n+Zt(o,e),n|=0;return Gt(n>>>0,16)})(Qn,Zn):void 0),no=(Mt({encode:e=>Ce(xe(e)),decode:e=>Ie(De(e))}),Mt({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=zt(255&Zt(e,n));return $e(t)},decode:e=>Pe(e)}),e=>void 0!==Lt(e,"objUrl")),oo=e=>void 0!==Lt(e,"blob"),so=e=>void 0!==Lt(e,"dataUri"),ro=["chrome"];let io,ao,co,lo,uo,po;uo=()=>{if(void 0!==ao)return ao;try{
ao=-1!=navigator.userAgent.indexOf("Mac OS X")}catch(e){}return ao},lo=()=>{if(void 0!==io)return io;try{const e=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);e&&(io=parseInt(e[2]))}catch(e){}return io},po=()=>{if(void 0!==co)return co;try{co=-1!=navigator.userAgent.search(/Android|Mobile/)}catch(e){}return co};const mo=(lo(),!1),go=["chrome-extension:"],fo=globalThis,{chrome:_o,browser:vo}=fo,ho=([].concat(["chrome"]),function(e){
const t=()=>"prerender"!==document.webkitVisibilityState,n=()=>{t()&&(document.removeEventListener("webkitvisibilitychange",n,!1),e())};t()?e():document.addEventListener("webkitvisibilitychange",n,!1)}),wo=(()=>{const e={getInternalPathRegexp:function(e,t){const n=new RegExp("(\\"+["/",".","+","?","|","(",")","[","]","{","}","\\"].join("|\\")+")","g"),o=go[0]+"//"+wo.id+"/";return new RegExp(o.replace(n,"\\$1")+"([a-zA-Z"+(e?"\\/":"")+"]*)"+(t||"").replace(n,"\\$1"))},
getInternalPageRegexp:function(){return wo.getInternalPathRegexp(!1,".html")},getPlatformInfo:e=>_o.runtime.getPlatformInfo(e),getBrowserInfo:e=>{e({name:"Chrome",version:`${lo()}`,vendor:"unknown"})}};return Object.defineProperty(e,"lastError",{get:()=>_o.runtime.lastError,enumerable:!0}),Object.defineProperty(e,"id",{get:()=>_o.runtime.id,enumerable:!0}),Object.defineProperty(e,"short_id",{get:()=>e.id.replace(/[^0-9a-zA-Z]/g,"").substr(0,4),enumerable:!0}),e})(),bo=(()=>{const e={
getURL:function(e){return _o.runtime.getURL(e)},sendMessage:function(e,t){return _o.runtime.sendMessage(e,t)},onMessage:{addListener:function(e){return _o.runtime.onMessage.addListener(e)}},connect:function(e){return _o.runtime.connect({name:e})}};let t;return Object.defineProperty(e,"inIncognitoContext",{get:()=>(void 0===t&&(t=_o.extension.inIncognitoContext),t),set:e=>{t=e},enumerable:!0}),e})(),yo=_o.userScripts&&_o.userScripts.onBeforeScript?{supported:!0,onBeforeScript:{
addListener:e=>_o.userScripts.onBeforeScript.addListener(e)}}:{supported:!1},Mo=({sendPrefix:e,listenPrefix:t,send:n,onMessage:o})=>{if(void 0===n||void 0===o)throw"invalid args";let s,r,i=1;const a=Mt({}),c=Mt({}),d=e=>{e&&(s=e)},l=e=>{const t=++i;return c[i]=e,t};o(((o,i)=>o==`${t}_${s}`?(t=>{const{m:o,r:i,a:d,n:l}=t;if(a[o]&&(Tt(a[o],(e=>e(d))),delete a[o]),"message.response"==o){if(null==i)throw"Invalid Message";((e,t)=>{let n;e&&(n=c[e])&&(n(t),delete c[e])})(i,d)}else if(r){const t=i?t=>{
n(`${e}_${s}`,Mt({m:"message.response",a:t,r:i}))}:()=>{};r(Mt({method:o,args:d,node:l}),t)}})(i):null));const u=Mt({init:async e=>{s?d():d(e)},refresh:()=>null,switchId:e=>{s&&u.cleanup(),d(e)},send:(t,o,r,i)=>bn((a=>{let c,d;"function"!=typeof r&&null!==r?(c=r,d=i):d=r,n(`${e}_${s}`,Mt({m:t,a:o,r:d?l(d):null,n:c})),a()})),sendToId:(t,o,s)=>{n(`${e}_${t}`,Mt({m:o,a:s,r:null}))},once:(e,t)=>{a[e]||(a[e]=[]),$t(a[e],t)},setMessageListener:e=>{r=e},cleanup:()=>null});return u
},Eo=yo,Lo=yo.supported&&!_n.pagejs;let Oo;const So=(e,t)=>{try{Oo(e),t&&t()}catch(e){t&&t(e.message||e)}},xo="u"+yn(),{bridges:Io}=twod;let Ro=[];const jo=e=>{Eo.onBeforeScript.addListener((o=>{const s=(e,n)=>{Tt(t,(t=>t(e,n)))},r=e=>$t(n,Mt({listener:e,clone:o.export}));gt(o.global,"pagejs",Mt({set:o.export((t=>{delete o.global.pagejs;const n=o.metadata,{modes:i,nonce:a}=n;if(a&&eo(a),Tt(Ro,(e=>e(t,n))),Ro=[],i.js){const n=Mt({unsafeWindow:o.global,unsafeThis:o.global.window,pageWindow:void 0,
contextId:xo,fSend:s,fOnMessage:r,cloneInto:void 0,exportFunction:void 0});t(o.export(n)),Io.js.sendToId(xo,"commid",Mt({id:e}))}})),configurable:!0})),Oo=o.global.eval}));const t=[],n=[],o=(e,t)=>{Tt(n,(({listener:n,clone:o})=>n(e,o(t))))},s=e=>$t(t,e);return Mt({createBridge:()=>{const t=Mo(Mt({sendPrefix:"2S",listenPrefix:"2U",cloneInto:Gn,send:o,onMessage:s}));return t.init(e),t}})};let Do;const{console:Co}=twod,Po=e=>(e.details&&e.details.url,bn((async t=>{t(e)}))),$o=Mt({setInterval:e=>{
let t;e.onMessage.addListener((n=>{"setInterval"==n.method&&(t=Cn(e.postMessage,n.t))})),e.onDisconnect.addListener((()=>{t&&$n(t),t=null}))},registerMenuCommand:e=>{const t=bo.connect("registerMenuCommand");t.onMessage.addListener((n=>{if(null!==t){const{method:t,event:o}=n;e.postMessage(Mt({method:t,event:o}))}})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{if("register"!==e.method)return
;const{name:n,uuid:o,accessKey:s,autoClose:r,title:i}=e,a=Pt([Do,n,o],"#");t.postMessage(Mt({method:"registerMenuCommand",name:n,title:i,uuid:o,menuId:a,accessKey:s,autoClose:r}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))},openInTab:e=>{const t=bo.connect("openInTab");t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{if("openTab"==e.method){let n=e.url
;const{active:o,loadInBackground:s,insert:r,incognito:i,setParent:a}="boolean"==typeof e.options||void 0===e.options?Mt({loadInBackground:e.options}):e.options,c=void 0===o?void 0!==s&&!s:o,d=void 0===r||r;n&&"//"==Vt(n,0,2)&&(n=Xn.protocol+n),t.postMessage(Mt({method:"openInTab",details:Mt({url:n,options:Mt({active:!!c,insert:!!d,incognito:!!i,setParent:!i&&!!a})}),uuid:e.uuid}))}else void 0!==e.name?t.postMessage(Mt({name:e.name,uuid:e.uuid})):e.focus?t.postMessage(Mt({focus:!0,uuid:e.uuid
})):e.close&&t.postMessage(Mt({close:!0,uuid:e.uuid}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))},download:e=>{let t;const n=bo.connect("download");n.onMessage.addListener((t=>{e.postMessage(t)})),n.onDisconnect.addListener((()=>{e.disconnect(),t=!0})),e.onMessage.addListener((e=>{e.cancel?(t=!0,n.postMessage(Mt({cancel:!0,id:Do,uuid:e.uuid}))):Po(e).then((e=>{if(t)return;let{url:o,...s}=e.details;n.postMessage(Mt({method:"download",details:Mt({...s,from:Mt({url:o})}),id:Do,
uuid:e.uuid,location:Xn.href}))}))})),e.onDisconnect.addListener((()=>{n.disconnect()}))},webRequest:e=>{const t=bo.connect("webRequest");t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(Mt({method:"webRequest",rules:e.rules,uuid:e.uuid}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))},xhr:e=>{let t,n;const o=[],s=async e=>{if(e&&$t(o,e),n)await n,s();else{const e=Dt(o);e&&e()}
},r=bo.connect("xhr");r.onMessage.addListener((t=>{s((()=>{const{onpartial:o,data:s,...r}=t;let i;if(o&&s){const{tfd:t}=s;if(t){const s=(e=>e&&(oo(e)||no(e)||so(e))?(e=>{let t,n,o;if(no(e))t=e.objUrl.url;else if(oo(e))n=e.blob;else{if(!so(e))throw"incompatible TransferableData";o=e.dataUri}return Mt({toBlob:()=>bn((e=>{if(n)e(n);else if(t)try{Kt(Fn(t),(t=>{Kt(Hn(t),(t=>{e(t)}))}))}catch(t){e(void 0)}else{if(!o)throw"incompatible Transferable";e((e=>{let t;const n=Nt(e,","),o=un(n,0),s=un(n,1)
;t=-1!=Yt(o,"base64")?Pe(s):Ce(s);const r=un(Nt(o,":"),1),i=un(Nt(r,";"),0);return new ln([t],Mt({type:i}))})(o))}})),dispose:()=>{t&&rn(t),t=n=o=void 0}})})(e):void 0)(t);if(!s)return;return void(n=bn((async t=>{const a=()=>{n=null,t(),s&&s.dispose()};try{const t=await s.toBlob();if(!t)return void a();const n=t.type;let c;if(c="arrayBuffer"in t?await Jn(t):await Wn(new qn(t)),!c)return void a();i=Mt({nada:Mt({buffer:c,type:n})}),e.postMessage(Mt({...r,onpartial:o,data:i})),a()}catch(e){
Co.warn(e),a()}})))}i=s}else i=s;e.postMessage(Mt({...r,onpartial:o,data:i}))}))})),r.onDisconnect.addListener((()=>{s((async()=>{e.disconnect(),t=!0}))})),e.onMessage.addListener((e=>{Po(e).then((e=>{t||(e.location=Xn.href,r.postMessage(e))}))})),e.onDisconnect.addListener((()=>{r.disconnect()}))},onurlchange:e=>{const t=bo.connect("onurlchange");let n=()=>{e.postMessage(Mt({url:Xn.href}))};const o=()=>{n&&(wn.removeEventListener("hashchange",n),n=null)};wn.addEventListener("hashchange",n),
t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect(),o()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect(),o()}))},values:e=>{const t=bo.connect("values");t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))}}),Ao=Mt({setTimeout:({args:e,cb:t})=>{Pn(t,e.t)},
setClipboard:({args:e,cb:t})=>{const{content:n,info:o,uuid:s}=e;let r,i;"object"==typeof o?(o.type&&(r=o.type),o.mimetype&&(i=o.mimetype)):"string"==typeof o&&(r=o);const a=i||("html"==r?"text/html":"text/plain");mo?bo.sendMessage(Mt({method:"clipboard",mimetype:a,content:n,uuid:s}),(()=>t())):(_n.document.addEventListener("copy",(e=>{e.stopImmediatePropagation(),e.preventDefault(),e.clipboardData&&e.clipboardData.setData(a,n)}),Mt({capture:!0,once:!0})),_n.document.execCommand("copy"),t())},
notification:({args:e,cb:t})=>{e.method="notification",bo.sendMessage(e,(e=>t(e)))},closeTab:({args:{uuid:e},cb:t})=>{bo.sendMessage(Mt({method:"closeTab",uuid:e,id:Do}),(e=>{e&&e.error&&Co.warn(e.error),t(e)}))},focusTab:({args:{uuid:e},cb:t})=>{bo.sendMessage(Mt({method:"focusTab",uuid:e,id:Do}),(e=>{e&&e.error&&Co.warn(e.error),t(e)}))},addElement:async({args:t,node:n,cb:o})=>{try{const s=Kn(t.tag,Mt({...t.properties||Mt({}),...t.id?Mt({id:t.id}):Mt({})}));let r,i
;if("script"===t.tag&&(r=to())&&s.setAttribute("nonce",r),n)i=n;else{const t=_n.document;if(i=t.head||t.body||t.documentElement,!i){const t=_n.document;i=await bn((n=>e((()=>n(t.head||t.body)))))}}i.appendChild(s),r&&s.removeAttribute("nonce"),o()}catch(e){Co.warn("content: error adding script",e)}},tabs:({args:e,cb:t})=>{e.method="tabs",bo.sendMessage(e,(e=>e&&t(e.data)))},cookie:({args:e,cb:t})=>{e.method="cookie",bo.sendMessage(e,(e=>e&&t(e.data)))}}),To=Mt({init:()=>{Do=twod.contextId},
processMessage:({method:e,args:t,node:n},o)=>{let s;if(s=Ao[e])return s(Mt({args:t,node:n,cb:o}));o()},processConnect:(e,t)=>{let n;if(n=$o[e])return n(t)}}),Uo=["GM_info","GM.info"],No=["unsafeWindow",...Uo],Bo=e=>e.replace(new RegExp("[\"']","g"),"\\$1");let Fo=!1;const Xo=(e,t,n,o,s)=>{const{console:r}=twod;Fo=Fo||e.logLevel>=60;const{version:i,injectMode:a,inIncognitoContext:c,isFirstPartyIsolation:d,downloadMode:l,relaxedCsp:u,userAgent:p,container:m,logLevel:g}=e,f=Mt({version:i,
injectMode:a,inIncognitoContext:c,isFirstPartyIsolation:d,downloadMode:l,relaxedCsp:u,container:m});Tt(t,(async t=>{const{script:i,storage:a}=t,{name:c,uuid:d,options:{run_at:l}}=i,{requires:u,...m}=i,_=u.length,v=!i.options.unwrap,h=Mt({...f,userAgent:p,logLevel:g,sandboxMode:s});let w,b;const y=((e,t)=>{
const{measure_scripts:n,top_level_await:o,enforce_strict_mode:s}=e,{source_url:r,script:i,code:a}=t,{name:c,grant:d}=i,{requires:l}=i,u=!i.options.unwrap,p=l.map((e=>e.textContent||"")).join("\n");if(u){let e="";const t=["define","module","exports"],l=t.map((()=>"undefined")),u=-1!==i.grant.indexOf("none");let m;return m=u?Uo:d.concat(No),m.forEach((e=>{const n=e.split(".")[0];"window"!==n&&-1===t.indexOf(n)&&(t.push(n),l.push(`p.${n}`))})),
[`with (${u?"this.s":"this"}) {`,"(async (u, { p, r, s }) => {","try {",n?`console.time("${e=`SCRIPT RUN TIME[${Bo(c)}]`}");\n`:"","r(u, s, [",l.join(","),"]);",n?`console.timeEnd("${e}");\n`:"","} catch (e) {","if (e.message && e.stack) {","console.error(\"ERROR: Execution of script '",Bo(c),"' failed! \" + e.message);","console.log(e.stack);","} else {","console.error(e);","}","}","})","(",(o?"async ":"")+"function(",t.join(","),") {",s?'"use strict";\n':"\n",p,a,"\n",`}, ${u?"this":"seed"})`,"}","\n",r?`//# sourceURL=${r}\n`:""].join("")
}return[p,a,"\n",r?`//# sourceURL=${r}\n`:""].join("")})(e,t);return v?(w=()=>{Fo&&r.debug(`env: inject "${c}" now`);const e=`__f__${yn()}`,t=Mt({storage:a,script:m}),s=`window["${e}"] = function(){${y}}`;let i=!0;o.once(`scriptack-${e}`,(()=>{Fo&&!i&&r.log(`env: execution of "${c}" was delayed`),n(s,(e=>{e&&r.error(`Uncaught SyntaxError: ${e}`)}))})),o.send("script",Mt({id:e,unwrap:!1,bundle:t,flags:h})),i=!1},b="context-menu"==l||"document-start"==l?void 0:()=>{
Fo&&r.debug(`env: run "${c}" now  (${_} requires)`),o.send("run",Mt({uuid:d}))}):b=()=>{Fo&&r.debug(`env: inject @unwrap "${c}" now`),n(y,(e=>{e&&r.error(`Uncaught SyntaxError: ${e}`)}))},ko(c,l,w,b,Fo)}))},ko=(t,n,o,s,r)=>{const{console:i}=twod;let a;"document-start"==n?(r&&i.debug(`env: run "${t}" ASAP -> document-start`),a=e=>e()):"document-body"==n?(r&&i.debug(`env: schedule "${t}" for document-body`),
a=zn):"context-menu"==n?r&&i.debug(`env: run "${t}" ASAP -> context-menu`):"document-end"==n?(r&&i.debug(`env: schedule "${t}" for document-end`),a=t=>e(!1,t)):(r&&i.debug(`env: schedule "${t}" for document-idle`),a=Vn),o&&o(),s&&a&&a((()=>{s()}))},qo=e=>{let t=n=>{delete _n.pagejs,t=void 0,e(n)};gt(_n,"pagejs",Mt({set:t,configurable:!0})),Pn((()=>{t&&t()}),1)},Wo=(e,t)=>{const n=(e,t)=>{Tt(s,(n=>n(e,t)))},o=e=>$t(r,Mt({listener:e,clone:e=>e})),s=[],r=[],i=(e,t)=>{
Tt(r,(({listener:n,clone:o})=>n(e,o(t))))},a=e=>$t(s,e),c="c"+yn();let d;return Mt({createBridge:()=>(d=Mo(Mt({sendPrefix:"2S",listenPrefix:"2U",send:i,onMessage:a})),d.init(e),d),inject:()=>(t(Mt({unsafeWindow:_n,unsafeThis:vn,pageWindow:void 0,contextId:c,fSend:n,fOnMessage:o})),d.sendToId(c,"commid",Mt({id:e})),!0)})},Ho=(e,t)=>{let n,o;try{o=(0,eval)(e)}catch(e){n=e.message||e}return t&&t(n),o},{createEvent:Jo}=mn,Go=({sendPrefix:e,listenPrefix:t,cloneInto:o})=>{const s=Mt({});let r,i,a=1
;const c=Mt({});let d=!1,l=[];const u=()=>{_=_n.document.documentElement,d=!1;const e=l;l=[],Tt(e,(e=>{d||h()?$t(l,e):e()}))},p=e=>{const t=++a;return c[a]=e,t},m=(e,t)=>{const{m:n,a:s,r,n:i}=t,a=((e,t,n)=>{let s;var r;return n?(s=Jo("MutationEvent"),Ht(s,e,!1,!1,n||null,void 0,void 0,jt(t),Jt)):s=new cn(e,Mt({detail:(r=t,o?o(r,_n.document):r)})),s})(e,Mt({m:n,a:s,r}),i);yt(Te,_n,[a])},g=t=>{const{m:n,r:o,a}=kt("CustomEvent"==qt(d=t)?sn(d):Rt(nn(d)));var d;if(s[n]&&(Tt(s[n],(e=>e(a))),
delete s[n]),"unlock"==n)m(`${e}_${i}`,Mt({m:"unlocked",a:void 0,r:null})),u();else if("unlocked"==n)u();else if("message.response"==n){if(null==o)throw"Invalid Message";((e,t)=>{let n;e&&(n=c[e])&&(n(t),delete c[e])})(o,a)}else if(r){const s=o?t=>{m(`${e}_${i}`,Mt({m:"message.response",a:t,r:o}))}:()=>{};r(Mt({method:n,args:a,node:"MutationEvent"===qt(t)?on(t):void 0}),s)}},f=e=>{e&&(i=e),i&&wn.addEventListener(`${t}_${i}`,g,!0)};let _,v;const h=()=>{if((()=>{const e=_n.document.documentElement
;return _||(_=e),_!==e})()){if(v){const e=v;v=void 0,e(_n.document)}return!0}},w=Mt({init:async(t,o)=>{i?f():f(t),n&&!o&&await null,(_=_n.document.documentElement,bn((e=>{v=e;const t=new dn((()=>{h()&&t.disconnect()}));t.observe(_n.document,Mt({childList:!0}))}))).then((()=>{d=!0,w.refresh(),m(`${e}_${i}`,Mt({m:"unlock",a:void 0,r:null}))}))},refresh:()=>{const e=i;e&&(w.cleanup(),w.init(e,!0))},switchId:e=>{i&&w.cleanup(),f(e)},send:(t,n,o,s)=>bn((r=>{let a,c
;"function"!=typeof o&&null!==o?(a=o,c=s):c=o,h();const u=()=>{m(`${e}_${i}`,Mt({m:t,a:n,r:c?p(c):null,n:a})),r()};d?$t(l,u):u()})),sendToId:(t,n,o)=>{m(`${e}_${t}`,Mt({m:n,a:o,r:null}))},setMessageListener:e=>{r=e},once:(e,t)=>{s[e]||(s[e]=[]),$t(s[e],t)},cleanup:()=>{i&&(wn.removeEventListener(`${t}_${i}`,g,!0),i=void 0)}});return w},Ko=function(e,t,n,o,s){let r;const i=to(),a=Kn("script");i&&a.setAttribute("nonce",i);try{a.textContent=t,e.appendChild(a)}catch(e){r=e.message||e}
if(i&&a.removeAttribute("nonce"),!s){const e=a.parentNode;e&&e.removeChild(a)}return o&&o(r),!r},zo=(e,t)=>{try{Ko(kn.head||kn.body||kn.documentElement||kn,e,0,t)}catch(e){t&&t(e.message||e)}},Vo=(e,t)=>{const n=un(tn(_n.document,"*"),0)||_n.document,o=Kn("div"),s=o.attachShadow(Mt({mode:"closed"}));s.appendChild(Kn("style",":host { display: none }"));const r=Kn("iframe",Mt({sandbox:"allow-scripts allow-same-origin",style:"display: none",src:"javascript:void 0"}));let i=()=>{if(null===i)return
;i=null;let n=!1;try{const t=r.contentDocument,o=r.contentWindow;t&&o&&(n=Ko(un(t.getElementsByTagName("*"),0),e))}catch(e){}t(o,n),r.remove(),o.remove()};r.addEventListener("load",i,Mt({once:!0,capture:!0})),s.appendChild(r),n.appendChild(o),i&&i()};let Yo=!1;const Zo=location.pathname+location.search,Qo="TM_"+wo.short_id+window.btoa(Zo.length+Zo).substr(0,255).replace(/[#=/]/g,"_"),es=()=>{let e,t,n,o;try{o=document.cookie.split(";")}catch(e){return}
for(e=0;e<o.length;e++)if(t=o[e].substr(0,o[e].indexOf("=")),n=o[e].substr(o[e].indexOf("=")+1),t=t.replace(/^\s+|\s+$/g,""),0===t.indexOf(Qo)){document.cookie=t+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;";const e=Ie(n);if(0!==e.indexOf("blob:"))continue;let o;try{if(0!==(new URL(e).origin+"/").indexOf(bo.getURL("/")))continue;if(o=new XMLHttpRequest,o.open("GET",e,!1),o.send(null),200===o.status||0===o.status)return JSON.parse(o.responseText)}catch(e){
console.warn("content: unable to decode "+(o&&o.responseText||"unknown"))}}};let ts=!1;const ns=(t,n,o)=>{const{contextId:s,bridges:r,console:i}=twod;let a;bn((e=>{const o=t=>{let n=1;const o=()=>{Yo&&i.log('content: send "prepare" message'),bo.sendMessage({method:"prepare",id:s,topframe:An,url:window.location.href},(s=>{if(!ts){if(!s)return Yo&&i.log("content: _early_ execution, connection to bg failed -> retry!"),window.setTimeout(o,n),void(n*=2);ts=!0,s.nonce&&eo(s.nonce),
ut(s.contexters).length||ut(s.scripts).length||s.external_connect?(t&&t(s),e({info:s,type:"complete"==Qt(_n.document)?"late":"normal"})):e({info:s})}}))};ho(o)},r=()=>{let r;if(Yo&&i.log("content: Started ("+s+", "+window.location.origin+window.location.pathname+")",vn.tm_info),(r=vn.tm_info)||(r=es())){delete vn.tm_info,r.nonce&&eo(r.nonce);const{contexters:o,scripts:s,external_connect:i,originalURL:c}=r;if(ut(o).length||ut(s).length||i){
if(r.contexters.raw||r.scripts.raw)if(t.raw)a=t.raw();else if(!n)throw"raw inject missing";e({info:r,type:"sync"})}else e({info:r});bo.sendMessage({method:"prepare",url:window.location.href,cleanup:!0},(()=>null))}else n?o((({scripts:e,contexters:n})=>{t.raw&&(e.raw||n.raw)&&(a=t.raw())})):(t.raw&&(a=t.raw()),o())};n?window.setTimeout((()=>r()),1):r()})).then((({info:a,type:c})=>{const{external_connect:d}=a;if(d&&(async()=>{await null,r.first.send("external.connect")})(),c){Yo=Yo||a.logLevel>=60
;const{scripts:d}=a;if(d.raw){let e;n&&!t.raw&&(e=!0),e&&(t.js?(d.js=(d.js||[]).concat(d.raw||[]),delete d.raw):t.dom&&(d.dom=(d.dom||[]).concat(d.raw||[]),delete d.raw))}if(d.js){if(!t.js)throw"js inject missing";t.js()}if(d.dom){if(!t.dom)throw"dom inject missing";t.dom()}e(!1,(()=>{Yo&&i.log("content: DOMContentLoaded"),Tt(ut(r),(e=>r[e].send("DOMContentLoaded")))})),l=()=>{Yo&&i.log("content: load"),Tt(ut(r),(e=>r[e].send("load")))},
"complete"==Qt(_n.document)?l():wn.addEventListener("load",(()=>l()),Mt({capture:!0,once:!0}));const u=(d.dom||[]).length+(d.js||[]).length+(d.raw||[]).length;Yo&&i.log("content: "+(c||"normal")+" start event processing for "+s+" ("+u+" to run)"),os(a,"sync"===c),!An&&u&&window.addEventListener("unload",(()=>{bo.sendMessage({method:"unLoad",id:s,topframe:!1,url:window.location.href},(()=>null))}),!1),o()}else o();var l}))},os=e=>{const{bridges:t}=twod,{scripts:n,...o}=e
;n.js&&Xo(o,n.js,So,t.js,"js"),n.dom&&(Tt(ro,(e=>vn[e]=void 0)),Xo(o,n.dom,Ho,t.dom,"dom")),n.raw&&Xo(o,n.raw,zo,t.raw,"raw")},ss=async()=>{const{contextId:e}=twod,{location:t,document:n}=_n;n.addEventListener("mouseenter",(()=>{bo.sendMessage(Mt({method:"contextmenu",url:t.href,id:e}),(()=>{}))}),!1)};let rs;(async()=>{const{unsafeWindow:e,bridges:n}=twod,{location:o,document:s}=e,r=s instanceof XMLDocument;if(!Mt({"http:":!0,"https:":!0,"file:":!0})[e.location.protocol])return
;const i=twod.contextId?twod.contextId:twod.contextId=yn();let a;const c=Mt({});mt(twod.console,Dn),bn((t=>{if(Lo){const{createBridge:e}=jo(i);$t(Ro,((o,s)=>{rs=a=o;const{modes:i}=s;i.js&&(n.js=e(),c.js=()=>!1,r&&(i.raw=!1)),t(s)}))}else bn((t=>{rs=a=e.pagejs,delete e.pagejs,rs?t():qo((e=>{if(!e)throw"Error: pagejs missing. Please see http://tmnk.net/faq#Q208 for more information.";rs=a=e,t()}))})).then((()=>{t(Mt({modes:Mt({js:!1,raw:!0,dom:!0})}))}))
})).then((({modes:{dom:s,raw:d},answer:l})=>{var u;if(l&&(u=l).scripts&&u.contexters&&(vn.tm_info=l),s){const e=Lo?Ho(`() => ${a};`)():a,{createBridge:t,inject:o}=Wo(i,e);c.dom=o,n.dom=t()}if(d){const{createBridge:e,inject:o}=((e,n)=>{let o;return Mt({createBridge:()=>(o=Go(Mt({sendPrefix:"2P",listenPrefix:"2C",cloneInto:Gn})),o),inject:()=>{o.init(e);let s=!1;{const r=yn(),i="("+Wt(((e,t)=>{const n=window,o=t(n),s=n.parent,{O_dPy:r,cSO:i}=o;r(s,e,i({value:o,enumerable:!1,writable:!1,
configurable:!0}))}))+')("'+r+'", '+Wt(t)+")";o.once("ack",(()=>{s=!0})),(t=>{Vo(t,((t,s)=>{Ko(t,`(${n})({ unsafeWindow: typeof globalThis === "undefined" ? window : globalThis, unsafeThis: window, vault: ${s?`window["${r}"]`:"null"}, contextId: "${r}", __proto__: null });delete window["${r}"]\n`,0,(()=>{o.sendToId(r,"commid",Mt({id:e}))}),!0)}))})(i)}return s}})})(i,a);c.raw=o,n.raw=e()}n.first=n.js||n.raw||n.dom,bo.onMessage.addListener(((t,s,r)=>{
"executeScript"==t.method?(t.url&&0!==Yt(o.href,t.url)||void 0!==t.topframe&&t.topframe!=An||os(t.info,!1),r(Mt({}))):An&&("loadUrl"==t.method?(e.location=t.url,r(Mt({}))):"reload"==t.method?(o.reload(),r(Mt({}))):"setForeignAttr"==t.method?(n.first.send(t.method,t),r(Mt({}))):Dn.log("content: unknown method "+jt(t)))})),Mn.onConnect.addListener(((e,t)=>{To.processConnect(e,t)})),To.init(),Tt(ut(n),(e=>{if("first"==e)return;const t=n[e];t.setMessageListener(((n,o)=>{const{method:s,args:r}=n
;if("port.message"==s)Mn.message(r,t);else if("csp"==s){let t;t="raw"==e?zo:"dom"==e?Ho:So,t(r.src,(e=>{e&&Dn.error(`Uncaught Error: ${e}`)}))}else if("external.message"==s)bo.sendMessage(Mt({method:"externalMessage",request:r}),(e=>{o(e)}));else if("console"==s){const e=r,t=un(e,0),n=un(e,1),o=Dn[t]||Dn.log;o&&yt(o,Dn,((e,...t)=>{let n=e.length;const o=Mt(e);for(let e=0;e<t.length;e++){const s=t[e],r=ht(s)?s:[s];for(let e=0;e<r.length;e++)o[n+e]=Lt(r,e);n+=r.length}return pt(o)
})(["injected:"],(e=>{const t=[];return Tt(e,(e=>{$t(t,(e=>"string"==typeof e?Rt(e):e)(e))})),t})(n)))}else To.processMessage(n,o)}))})),ns(c,r,(()=>rs=void 0)),ss()}))})()})();})({ __proto__: null, unsafeWindow: typeof globalThis === "undefined" ? window : globalThis, unsafeThis: window, }, "tm_hfk8qg")