this.pagejs=e=>{(()=>{"use strict";const t="vault"in e;if(t&&void 0===e.vault)throw"Invalid vault";const n=e.vault=e.vault||(e=>{const t=Object.call,n=t.bind(t),o=Object.assign,r=Object.getOwnPropertyDescriptor,s=e=>o({__proto__:null},e);return s({sourceWindow:e,cSO:s,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sh:[].shift,A_j:[].join,A_f:[].filter,A_iO:[].indexOf,A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,
O_dP:Object.defineProperties,O_dPy:Object.defineProperty,O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:r,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:Object.getPrototypeOf,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_i:MutationEvent.prototype.initMutationEvent,M_pA:MutationEvent.prototype.ADDITION,M_pAT:MutationEvent.AT_TARGET,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,
P_c:Promise.prototype.catch,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,R_r:r(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,
S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,
E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,D_cS:r(Document.prototype,"currentScript").get,D_gRS:r(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_aN:r(MutationEvent.prototype,"attrName").get,M_rN:r(MutationEvent.prototype,"relatedNode").get,C_d:r(CustomEvent.prototype,"detail").get,W_aEL:addEventListener,W_rEL:removeEventListener,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,
MouseEvent,MutationEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,alert,prompt,confirm,close,getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,
createElement:e.Document.prototype.createElement})
})(e.unsafeWindow),{cSO:o,F_c:r,F_a:s,F_b:a,F_tS:i,A_fE:l,A_so:c,A_sh:d,A_j:u,A_f:p,A_iO:g,A_iA:f,O_a:v,O_k:m,O_v:_,O_dP:b,O_dPy:M,O_hOP:h,O_gOPN:y,O_gOPD:w,O_gOPDs:E,O_gPO:S,O_tS:G,J_p:R,J_s:O,M_f:L,M_r:C,M_m:T,M_i:x,M_pA:I,M_pAT:D,N_tS:A,N_MSI:P,P_t:k,P_c:U,R_rABS:$,R_rAT:F,R_r:j,R_enq:N,R_cl:V,S_fCC:q,S_sl:X,S_su:B,S_iO:H,S_sp_nr:W,S_tr:K,S_rA_nr:J,S_cCA:z,S_tLC:Y,S_tUC:Q,Y_tST:Z,D_pFS:ee,D_cS:te,D_gRS:ne,D_cE:oe,D_gEBT:re,E_r:se,E_s:ae,M_aN:ie,M_rN:le,C_d:ce,U_cOU:de,U_rOU:ue,X_o:pe,X_s:ge,X_pSD:fe,X_pSH:ve,X_pSL:me,X_pSO:_e,X_pSU:be,D_n:Me,I_tS:he,W_aEL:ye,W_rEL:we,parseInt:Ee,parseFloat:Se,console:Ge,encodeURIComponent:Re,decodeURIComponent:Oe,encodeURI:Le,decodeURI:Ce,escape:Te,unescape:xe,atob:Ie,btoa:De,postMessage:Ae,dispatchEvent:Pe,alert:ke,prompt:Ue,confirm:$e,close:Fe,getElementById:je,createEvent:Ne,createElement:Ve,CustomEvent:qe,CompositionEvent:Xe,KeyboardEvent:Be,MouseEvent:He,MutationEvent:We,MutationObserver:Ke,Uint8Array:Je,FileReader:ze,DOMParser:Ye,XMLHttpRequest:Qe,Function:Ze,RegExp:et,Promise:tt,Blob:nt,ReadableStream:ot,Number:rt,String:st,Proxy:at,Window:it}=n,lt=r,ct=s,dt=m,ut=_,pt=v,gt=b,ft=M,vt=y,mt=w,_t=S,bt=E||(e=>{
const t=St({});for(const n in e)t[n]=mt(e,n);return t}),Mt=f,ht=L,yt=C,wt=T,Et=(e,t,n)=>lt(ct,e,t,n),St=o,Gt=(e,t,n)=>(ft(e,t,St({value:n,configurable:!0,enumerable:!0,writable:!0})),e),Rt=(e,t)=>Bt(e,t)?e[t]:void 0,Ot=(e,t)=>{const n=mt(e,t);return n?St(n).value:void 0},Lt=(e,t)=>{const n=(e,t,o)=>{const r=mt(e,t),s=r?St(r):void 0;let a;return s?s.enumerable?s.value:void 0:--o>=0&&(a=_t(e))?n(a,t,o):void 0};return n(e,t,5)},Ct=e=>{const t=(t,...n)=>Et(e,t,n);return Gt(t,"wrappedJSObject",e),t
},Tt=()=>e=>Ct(e),xt=Ct(a),It=R,Dt=e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const r=typeof e;if("object"===r){if(n){if(-1!=qt(n,e))throw"Converting circular structure to JSON";Gt(n,n.length,e)}else n=[e];if(Mt(e)){let r="";for(let o=0;o<e.length;o++){let s;s=Bt(e,o)?Rt(e,o):Lt(e,o);const a=t(s,n);r+=`${o?",":""}${void 0===a?"null":a}`}o=`[${r}]`}else{let r="";Xt(dt(e),(o=>{const s=t(e[o],n);void 0!==s&&(r+=`${r?",":""}${O(o)}: ${s}`)})),o=`{${r}}`}n.length-=1}else{
if("bigint"===r)throw"Do not know how to serialize a BigInt";o=O(e)}}return o};return t(e)},At=e=>{const t=R(e),n=e=>{const t=[];for(let n=0;n<e.length;n++)Gt(t,n,o(e[n]));return t},o=e=>{if(null===e);else if("object"==typeof e){if(Mt(e))return n(e);{const t={};return Xt(dt(e),(r=>{const s=e[r];let a;a="object"==typeof s?Mt(s)?n(s):o(s):s,Gt(t,r,a)})),t}}return e};return o(t)},Pt=Tt()(c),kt=(e,t,n,...o)=>{const r=o||[],s=Ft(e,0,t),a=Ft(e,t,n),i=Ft(e,t+n);let l=Nt([],s);return l=Nt(l,r),
l=Nt(l,i),St({result:l,removed:a})},Ut=Tt()(d),$t=Tt()(p),Ft=(e,t,n)=>{const o=e.length;let r=t||0;if(r>=o)return[];r<0&&(r=wt(0,o+r));let s=void 0===n?o:n;s<0&&(s=wt(0,o+s)),s>o&&(s=o);const a=St({});for(let t=r;t<s;t++)a[t]=Ot(e,t);return ut(a)},jt=Tt()(u),Nt=(e,...t)=>{let n=e.length;const o=St(e);for(let e=0;e<t.length;e++){const r=t[e],s=Mt(r)?r:[r];for(let e=0;e<s.length;e++)o[n+e]=Ot(s,e);n+=s.length}return ut(o)},Vt=(e,t)=>{let n=e.length||0;return Gt(e,n,t),n++,e.length=n
},qt=Tt()(g),Xt=Tt()(l),Bt=Tt()(h),Ht=Tt()(W),Wt=Tt()(X),Kt=Ct(G),Jt=_t({}),zt=e=>{const t=St(e),n=vt(t);for(let e=0;e<n.length;e++){const o=n[e],r=t[o];null!==r&&"object"==typeof r&&_t(r)===Jt&&(t[o]=zt(r))}return t},Yt=e=>{const t=Ht(Kt(e)," ");return Wt(jt(Ft(t,1)," "),0,-1)},Qt=(Tt()(i),Tt()(x)),Zt=I,en=D,tn=Tt()(A),nn=P,on=async e=>e,rn=Tt()(k),sn=Tt()(U),an=Tt()($),ln=Tt()(F),cn=Tt()(j),dn=N?Tt()(N):N,un=V?Tt()(V):V,pn=q,gn=Tt()(B),fn=Tt()(H),vn=Tt()(K),mn=(Tt()(J||function(e,t){
return jt(Ht(this,e),t)}),Tt()(z)),_n=Tt()(Y),bn=Tt()(Q),Mn=Z,hn=Ct(ee),yn=Ct(te),wn=Ct(ne),En=(Ct(oe),Ct(re),Ct(se)),Sn=Ct(ae),Gn=Ct(ie),Rn=Ct(le),On=Ct(ce),Ln=(Tt()(pe),fe),Cn=ve,Tn=me,xn=_e,In=be,Dn=(Tt()(ge),Me),An=at,Pn=rt,kn=qe,Un=Be,$n=He,Fn=Je,jn=Ke,Nn=nt,Vn=function(e,t){return Ot(e,t)},qn=St({addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,MutationEvent:!0,Number:!0,
Object:!0,Promise:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),Xn=(()=>{const e=St({getElementById:je,createEvent:Ne,createElement:Ve,dispatchEvent:Pe,addEventListener,removeEventListener}),t=St({});return Xt(dt(e),(n=>{try{const o=e[n];t[n]=function(...e){return Et(o,Wn.document,e)}}catch(e){t[n]=((e,t)=>{if(Jn.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}
})(e,`document.${n}`)}})),t})(),Bn=St({top:!0,location:!0}),Hn=e,{unsafeWindow:Wn,unsafeThis:Kn}=Hn;e.bridges=e.bridges||St({});const Jn=e.console=e.console||St({}),zn=St({addEventListener:xt(ye,Wn),removeEventListener:xt(we,Wn)});Xt(dt(Bn),(async e=>{if(!zn[e])try{const t=Wn[e];if(null==t)return;zn[e]=t}catch(e){}})),Xt(dt(qn),(async e=>{if(!zn[e])try{let t=Ot(Wn,e);if(void 0===t&&(Kn===Wn||void 0===(t=Ot(Kn,e))))return;const n=qn[e];zn[e]=!1===n&&"function"==typeof t?xt(t,Kn):t}catch(e){}}))
;const Yn=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],Xt(t,(t=>t(e)))}else t=e;o=!0}}));const r=St({then:e=>(o?e(t):Vt(n,e),r)});return r},{createEvent:Qn}=Xn,Zn=()=>tn(Dn()+19831206*yt()+1,36),eo=async e=>{await null,e()},to=(()=>{const{console:t,bridges:n}=e,o=St({});let r;const s=(e,t)=>{let n=[],r=[];const s=()=>{n=[],r=[],a=null,delete o[e]};let a=St({postMessage:n=>{t.send("port.message",St({response_id:e,value:n}))},onMessage:St({addListener:e=>{Vt(n,e)}}),
onDisconnect:St({addListener:e=>{Vt(r,e)}}),disconnect:()=>{t.send("port.message",St({response_id:e,disconnect:!0})),s()}});return o[e]=St({message:e=>{n&&Xt(n,(t=>t(e)))},disconnect:()=>{r&&Xt(r,(e=>e())),s()}}),a};return St({message:(e,n)=>{let a;if(e.connect){if(!e.destination||!e.response_id)throw"invalid message";r&&r(e.destination,s(e.response_id,n))}else{if(!e.response_id)throw"invalid message";if(!(a=o[e.response_id]))return void t.warn("ports: unkown id",e.response_id,e)
;e.disconnect?a.disconnect():a.message(e.value)}},connect:e=>{const t=Zn();return n.first.send("port.message",St({response_id:t,connect:!0,destination:e})),s(t,n.first)},onConnect:St({addListener:e=>{r=e}})})})(),{bridges:no}=e,oo=St({}),ro=St({});let so=!0,ao=[];eo((()=>{so=!1,Xt(ao,(({m:e,i:t})=>no.first.send("console",[e,t]))),ao=[]})),Xt(["debug","log","info","warn","error"],(e=>{Gt(oo,e,((...t)=>{const n=(e=>{const t=[];return Xt(e,(e=>{Vt(t,(e=>Dt(e))(e))})),t})(t);if(so)return Vt(ao,St({
m:e,i:n}));no.first.send("console",[e,n])}))}));const io=St(bt(Wn.console)),lo=St({});Xt(vt(Ge),(e=>{const t=St(io[e]);lo[e]=St({get:"value"in t?()=>t.value:t.get,enumerable:!0,configurable:!1})})),gt(ro,lo)
;const co=["chrome"],uo=["GM_addElement","GM.addElement","GM_addStyle","GM.addStyle"],po=["GM_cookie","GM.cookie"],go=["GM_listValues","GM.listValues","GM_getValue","GM.getValue","GM_addValueChangeListener","GM.addValueChangeListener","GM_removeValueChangeListener","GM.removeValueChangeListener"],fo=["GM_setValue","GM.setValue","GM_deleteValue","GM.deleteValue"],vo=["GM_download","GM.download"],mo=["GM_getResourceText","GM.getResourceText","GM_getResourceURL","GM.getResourceUrl"],_o=["GM_getTab","GM.getTab","GM_getTabs","GM.getTabs","GM_saveTab","GM.saveTab"],bo=["GM_log","GM.log"],Mo=["GM_notification","GM.notification"],ho=["GM_openInTab","GM.openInTab"],yo=["GM_registerMenuCommand","GM.registerMenuCommand","GM_unregisterMenuCommand","GM.unregisterMenuCommand"],wo=["GM_setClipboard","GM.setClipboard"],Eo=["GM_xmlhttpRequest","GM.xmlHttpRequest"],So=["window.close"],Go=["window.focus"],Ro=["window.onurlchange"],Oo=["GM_webRequest","GM.webRequest"],Lo=St({
encode:e=>xe(Re(e)),decode:e=>Oe(Te(e))}),Co=St({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=pn(255&mn(e,n));return De(t)},decode:e=>Ie(e)}),To=e=>{const t=new Fn(e.length);for(let n=0;n<e.length;n++)t[n]=mn(e,n);return t.buffer},xo=(e,t)=>Yn((n=>{const o=new zn.FileReader;o.onload=()=>{n(cn(o))},o.onerror=e=>{Jn.warn(`unable to decode data ${e}`),n("")},t?ln(o,e,t):an(o,e)})),{bridges:Io}=e;let Do=0,Ao=0;const Po=St({}),ko=St({}),Uo=function(e,t,n,o){const r=()=>{Po[n]&&(Et(e,this,o),
delete Po[n])};"function"==typeof e&&(Po[n]=e,0===t?eo((()=>r())):Io.first.send("setTimeout",St({t:t||1}),(()=>r())))},$o=e=>{const t=ko[e];t&&(t.disconnect(),delete ko[e])},Fo=(e,t,...n)=>{const o=Zn();return Uo(e,t,o,n),o},jo=e=>{(e=>{delete Po[e]})(e)},No=e=>$o(e),Vo=(e,t,...n)=>{const o=++Ao;return t=wt(t,1),Uo(e,t,o,n),o},qo=(e,t,...n)=>{const o=++Do;return function(e,t,n,o){if("function"==typeof e){const r=ko[n]=to.connect("setInterval");r.onMessage.addListener((()=>{ko[n]&&Et(e,this,o)
})),r.onDisconnect.addListener((()=>$o(n))),r.postMessage(St({method:"setInterval",t:t||1}))}}(e,t=wt(t,1),o,n),o},Xo=t=>{const{contextId:n,bridges:o}=e,r=St({}),s=(e,t)=>Pt(t,(t=>-1!=qt(e,t))),a=e=>function(){const t=on(Et(e,this,arguments));return Gt(t,"then",(e=>rn(t,e))),Gt(t,"catch",(e=>sn(t,e))),t},i=(e,t)=>function(...n){const o=[];if(void 0!==t)for(let e=0;e<t;e++)Vt(o,Vn(n,e)||void 0);return new zn.Promise((t=>{Et(e,this,Nt(o,[t]))}))},l=(e,t)=>{let n;const o=new zn.Promise(((o,r)=>{
const s=St({}),a=t.onload,i=t.ontimeout,l=t.onerror;Xt(dt(t),(e=>{s[e]=t[e]})),s.onerror=function(e){r(e),l&&Et(l,this,arguments)},s.ontimeout=function(e){r(e),i&&Et(i,this,arguments)},s.onload=function(e){o(e),a&&Et(a,this,arguments)};const c=e(s).abort;!0===n?c():n=c}));return Gt(o,"abort",(()=>{"function"==typeof n?n():n=!0})),o};return St({of:e=>{const c=e.script,d=(()=>{const e=s(c.grant,wo),t=(e,t,r)=>{o.first.send("setClipboard",St({content:e,info:t,id:n,uuid:c.uuid}),r?()=>r():null)}
;return St({GM_setClipboard:e?St({value:t}):void 0,"GM.setClipboard":e?St({get:()=>i(t,2)}):void 0})})(),u=(()=>{let t=[];const o=e.storage;let r=0,i=null;const l=s(c.grant,go),d=s(c.grant,fo),u=(e,t)=>{if("string"!=typeof e)return t;{const n=gn(e,0,1);switch(e=gn(e,1),n){case"b":return"true"===e;case"n":return Pn(e);case"x":try{return Lo.decode(Co.decode(e))}catch(t){return e}case"o":try{return At(e)}catch(e){Jn.log(`values: parseValueFromStorage: ${e}`)}return t;case"u":return;default:return e
}}},p=(e,n,o,r)=>{n!=o&&Xt(t,(t=>{if(t&&t.key==e&&t.cb)try{t.cb(e,u(n),u(o),r)}catch(t){Jn.warn(`values: change listener of "${e}" failed with: ${t.message}`)}}))},g=(e,t)=>{i&&i.postMessage(St({method:"saveStorageKey",uuid:c.uuid,key:e,value:o.data[e],removed:t,id:n,ts:o.ts}))};(l||d)&&(i=to.connect("values"),i.onDisconnect.addListener((()=>{i=null}))),i&&l&&(i.onMessage.addListener((e=>{const{storage:t,removed:n}=e;if(!t)return;const r=t,s=dt(r);n&&Vt(s,n),Xt(s,(e=>{const t=o.data[e],n=r[e]
;void 0===n?delete o.data[e]:o.data[e]=n,p(e,t,n,!0)}))})),i.postMessage(St({method:"addStorageListener",uuid:c.uuid,id:n})));const f=(e,t)=>u(o.data[e],t),v=()=>dt(o.data),m=(e,n)=>{const o=++r,s=St({id:o,key:e,cb:n});return Vt(t,s),o},_=e=>{t=$t(t,(t=>t.id!==e))},b=(e,t)=>{const n=o.data[e];o.ts=Dn(),o.data[e]=(e=>{const t=typeof e;let n,o=gn(t,0,1);switch(t){case"object":try{n=o+Dt(e)}catch(e){return void Jn.log(e)}break;case"function":case"symbol":case"bigint":o="u",n=o+void 0;break
;case"string":case"number":case"undefined":case"boolean":n=o+e;break;default:n=t}return n})(t),g(e),p(e,n,o.data[e],!1)},M=e=>{const t=o.data[e];o.ts=Dn(),delete o.data[e],g(e,!0),p(e,t,o.data[e],!1)};return St({GM_getValue:l?St({value:f}):void 0,"GM.getValue":l?St({get:()=>a(f)}):void 0,GM_listValues:l?St({value:v}):void 0,"GM.listValues":l?St({get:()=>a(v)}):void 0,GM_addValueChangeListener:l?St({value:m}):void 0,"GM.addValueChangeListener":l?St({get:()=>a(m)}):void 0,
GM_removeValueChangeListener:l?St({value:_}):void 0,"GM.removeValueChangeListener":l?St({get:()=>a(_)}):void 0,GM_setValue:d?St({value:b}):void 0,"GM.setValue":d?St({get:()=>a(b)}):void 0,GM_deleteValue:d?St({value:M}):void 0,"GM.deleteValue":d?St({get:()=>a(M)}):void 0})})(),p=(()=>{const e=s(c.grant,Ro),t=(()=>{let e=[],t=null;return St({register:o=>{Vt(e,o),t||(t=to.connect("onurlchange"),t.onMessage.addListener((({url:t})=>{t&&Xt(e,(e=>e(St({url:t}))))})),t.postMessage(St({
method:"observeUrlChanges",uuid:c.uuid,id:n})))},unregister:n=>{let o;n&&(o=qt(e,n))>-1&&(e=kt(e,o,1).result),t&&0===e.length&&(t.disconnect(),t=null)}})})();return St({"window.onurlchange":e?St({value:t}):void 0})})(),g=(()=>{const e=s(c.grant,mo),t=e=>{for(let t=0;t<c.resources.length;t++){const n=c.resources[t];if(n.name==e){if(n.error)Jn.warn("@resource: "+n.error);else try{if("string"==typeof n.content)return Lo.decode(n.content)}catch(e){}return""}}return null},n=e=>{
for(let t=0;t<c.resources.length;t++){const n=c.resources[t];if(n.name==e){if(n.error)Jn.warn("@resource: "+n.error);else if("string"==typeof n.content){try{return`data:${n.meta||"application/octet-stream"};base64,${Co.encode(n.content)}`}catch(e){}return n.url}return""}}return null};return St({GM_getResourceText:e?St({value:t}):void 0,"GM.getResourceText":e?St({get:()=>a(t)}):void 0,GM_getResourceURL:e?St({value:n}):void 0,"GM.getResourceUrl":e?St({get:()=>a(n)}):void 0})})(),f=(()=>{
const e=s(c.grant,_o),t=(e,t)=>{o.first.send("tabs",St({action:"set",uuid:c.uuid,tab:e}),t?()=>t():null)},n=e=>{o.first.send("tabs",St({action:"get",uuid:c.uuid}),e?t=>{e(t||St({}))}:null)},r=e=>{o.first.send("tabs",St({action:"list",uuid:c.uuid}),e?t=>{e(t||St({}))}:null)};return St({GM_saveTab:e?St({value:t}):void 0,"GM.saveTab":e?St({get:()=>i(t,1)}):void 0,GM_getTab:e?St({value:n}):void 0,"GM.getTab":e?St({get:()=>i(n)}):void 0,GM_getTabs:e?St({value:r}):void 0,"GM.getTabs":e?St({
get:()=>i(r)}):void 0})})(),v=(()=>{const e=s(c.grant,Eo),o=e=>{const o=zt(e);let s=!1,a=()=>{s=!0};const i=(e,t)=>{t=t||St({}),e&&Fo((()=>{pt(t,r),Et(e,t,[t])}),1)},l=o.url;"object"==typeof l&&l.href&&(o.url=l.href);const d=(e,t)=>{const n=Yt(e);if("Blob"===n||"File"===n){const o=e;xo(o).then((e=>{t(St({type:n,value:e,meta:o.type,name:o.name,lastModified:o.lastModified}))}))}else if("FormData"===n){const n=e,o=n.keys();let r;const s=St({}),a=[];for(;!(r=o.next()).done;)Vt(a,r.value)
;const i=()=>{if(a.length){const e=Ut(a);let t=n.getAll(e);"[]"!==gn(e,-2)&&(t=Vn(t,0)),d(t,(t=>{s[e]=t,i()}))}else t(St({type:"FormData",value:s}))};i()}else if("Array"===n||"Object"===n){const o=e;let r,s,a=0,i=0;if("Object"===n){const e=dt(o);s=t=>t<e.length?e[t]:null,r=St({})}else s=e=>e<o.length?e:null,r=[];const l=()=>{const e=s(a);null===e?t(St({type:n,value:r})):d(o[e],(t=>{r[e]=t,a++,i++<1024?l():(i=0,Fo(l,1))}))};l()}else t(St({value:e}))},u=(e,t,n,o,r)=>{let s
;if(n)"stream"==o&&(s=n);else if("arraybuffer"==o)s=t||To(e||"");else if("blob"==o)s=new zn.Blob([t||To(e||"")],St({type:r}));else if("json"==o)s=At(e||"");else if("document"==o){const t=new zn.DOMParser,n=Vn(Ht(r||"text/xml",";"),0);try{s=hn(t,e||"",n)}catch(e){s=null}}else s=e||(t?(e=>{let t="";const n=new Fn(e);for(let e=0;e<n.length;e+=32687)t+=Et(pn,null,n.subarray(e,e+32687));return t})(t):"");return s};return(e=>{if(o.url){const t=gn(o.url,0,5);if(-1!=qt(["data:","blob:"],t))return e()}
if(!o.data)return e();d(o.data,(t=>{o.binary&&(t.type="Blob"),o.data=t,o.data_type="typified",e()}))})((()=>{if(s)return s=!1,void i(o.onabort);let e,r,l,d=to.connect("xhr"),p=[];const{method:g,url:f,redirect:v,headers:m,cookie:_,binary:b,nocache:M,revalidate:h,timeout:y,context:w,responseType:E,overrideMimeType:S,anonymous:G,fetch:R,user:O,password:L,data:C,data_type:T}=o,x=St({method:g,url:f,redirect:v,headers:m,cookie:_,binary:b,nocache:M,revalidate:h,timeout:y,responseType:E,
overrideMimeType:S,anonymous:G,fetch:R,user:O,password:L,data:C,data_type:T});if(x.headers){const e=x.headers;Xt(dt(e),(t=>{"cookie"===_n(t)&&(x.cookie=`${e[t]}`,delete e[t])}))}let I,D,A,P;d.postMessage(St({method:"xhr",details:x,callbacks:St({onloadstart:!!o.onloadstart,onload:!!o.onload,ondone:!!o.onloadend,onreadystatechange:!!o.onreadystatechange,onerror:!0,onabort:!!o.onabort,ontimeout:!!o.ontimeout,onprogress:!!o.onprogress,onuploadprogress:!(!o.upload||!o.upload.onprogress),onpartial:!0
}),id:n,location:zn.location.href,uuid:c.uuid,no_blob:"js"==t.sandboxMode}));const k=E?_n(E):"";let U;const $=async t=>{if(t&&(l||void 0!==e||void 0!==r)){if(S?P=S:t&&(P=(e=>{const t=St({});return e&&Xt(Ht(e,"\n"),(e=>{const n=Ht(e,":");if(n.length<2)return;const o=Vn(n,0);if(!o)return;const r=jt(Ft(n,1),":");t[_n(vn(o))]=vn(r||"")})),t})(t.responseHeaders)["content-type"]),I=e,l)A=l.stream;else if(r){const e=r;if(D=e.buffer,-1==qt(["blob","arraybuffer"],k)&&!I){let t
;Pt([P,e.type],(e=>t=((e,t,n,o)=>{const r=fn(e,t);if(-1==r)return;const s=gn(e,r+t.length),a=fn(s,";");return-1==a?o&&o.optionalEnd?s:void 0:gn(e,r+t.length,a)})(_n(e||""),"charset=",0,St({optionalEnd:!0}))));const n=new Nn([D]);U=xo(n,t),I=await U}U=void 0}else U&&await U;e=r=void 0}if(I||A||D){t.responseType=E,Xt(["response_data"],(e=>delete t[e]));const e=St({response:()=>u(I,D,A,k,P||"binary/octet-stream"),responseText:()=>u(I,D,A,"text",P),responseXML:()=>u(I,D,A,"document","text/xml")})
;Xt(dt(e),(n=>{ft(t,n,St({get(){try{return e[n]()}catch(e){Jn.warn(`${g}:`,e)}}}))}))}},F=[],j=async e=>{e&&Vt(F,e);{const e=Ut(F);e&&e()}};"stream"===k&&j((async()=>{l=await Yn((e=>{const t=new zn.ReadableStream(St({start:n=>{Fo((()=>e(St({stream:t,ctrl:n}))),0)},cancel:()=>{l&&(l.canceled||a(),l.canceled=!0)}}))}))})),d.onMessage.addListener((t=>j((()=>(async t=>{if(t.onpartial){const n=t.data,o=n,s=o.partial,a=n.nada;if(l){if(l.canceled)return;const e=dn||((e,t)=>e.enqueue(t))
;if(void 0!==s)e(l.ctrl,s);else if(void 0!==a){const t=new Fn(a.buffer);e(l.ctrl,t)}else Jn.error(`${g}:`,"data message without data?!")}else{let t;s&&Vt(p,s),a&&(t=a),void 0!==o.index&&o.index!==o.length-1||(p.length&&(e=jt(p,""),p=[]),r=t)}}else{const e=t.data;if(w&&(e.context=w),t.onload)await $(e),i(o.onreadystatechange,e),i(o.onload,e);else if(t.onreadystatechange)await $(e),4!=e.readyState&&i(o.onreadystatechange,e);else if(t.onerror)t.exception&&Jn.error(t.exception),
i(o.onerror,e);else if(t.onabort)i(o.onabort,e);else if(t.ondone)l&&!l.canceled&&(un||(e=>e.close()))(l.ctrl),await $(e),i(o.onloadend,e);else if(t.onloadstart)l&&await $(e),i(o.onloadstart,e);else if(t.onuploadprogress)o.upload&&i(o.upload.onprogress,e);else{const n=Vn($t(["onprogress","ontimeout"],(e=>!!t[e])),0)||"onerror";i(o[n],e)}}})(t))))),d.onDisconnect.addListener((()=>d=null)),a=()=>{d&&d.postMessage(St({cancel:!0}))}})),St({abort:()=>{a()}})},r=(()=>{const e=St({DONE:Ln,
HEADERS_RECEIVED:Cn,LOADING:Tn,OPENED:xn,UNSENT:In});return Xt(["text","arraybuffer","blob","document","json","stream"],(t=>{e[`RESPONSE_TYPE_${bn(t)}`]=t})),e})();return Xt(dt(r),(e=>Gt(o,e,r[e]))),St({GM_xmlhttpRequest:e?St({value:o}):void 0,"GM.xmlHttpRequest":e?St({get:()=>{const e=e=>l(o,e);return Xt(dt(r),(t=>Gt(e,t,r[t]))),e}}):void 0})})(),m=(()=>{const e=s(c.grant,Mo),t=(e,t,r,s)=>{let a=null;const i=["timeout","text","image","title","highlight","silent"],l=St({})
;if("object"==typeof e){const n=e;Xt(i,(e=>{l[e]=n[e]})),a=n.ondone,s=n.onclick,"function"==typeof t&&(a=t)}else l.image=r,l.text=e,l.title=t;l.text&&(l.image=l.image||c.icon64||c.icon||void 0,l.title=l.title||c.name),l.onclick=s,l.ondone=a||void 0,(e=>{const{text:t,title:r,image:s,highlight:a,silent:i,timeout:l,onclick:d,ondone:u}=zt(e),p=St({id:n,uuid:c.uuid,text:t,title:r,image:s,highlight:a,silent:i,timeout:l});t||a?o.first.send("notification",p,(e=>{d&&e.clicked&&d(),u&&u(!0===e.clicked)
})):Jn.warn("GM_notification: neither a message text nor highlight options were given!")})(l)};return St({GM_notification:e?St({value:t}):void 0,"GM.notification":e?St({get:()=>(e,n,o,r)=>{let s;return s="object"==typeof e?e:St({text:e,title:n,image:o,onclick:r}),new zn.Promise((e=>{const n=St({});Xt(dt(s),(e=>{n[e]=s[e]}));const o=n.ondone;n.ondone=function(...t){o&&Et(o,this,t),Et(e,this,t)},t(n)}))}}):void 0})})(),_=(()=>{let n;const o=()=>{if(!n){
const{script:o}=e,{antifeatures:r,author:s,blockers:a,copyright:i,deleted:l,description_i18n:c,description:d,downloadURL:u,fileURL:p,grant:g,header:f,homepage:v,icon:m,icon64:_,lastModified:b,name_i18n:M,name:h,namespace:y,position:w,resources:E,supportURL:S,system:G,updateURL:R,version:O,webRequest:L,options:{override:{orig_connects:C,orig_excludes:T,orig_includes:x,orig_matches:I},run_at:D,unwrap:A}}=o,{downloadMode:P,inIncognitoContext:k,relaxedCsp:U,isFirstPartyIsolation:$,sandboxMode:F,userAgent:j,version:N}=t,V=R||p,q=St({
antifeatures:r,author:s,blockers:a,connects:C,copyright:i,deleted:l,description_i18n:c,description:d,downloadURL:u,excludes:T,fileURL:p,grant:g,header:f,homepage:v,icon:m,icon64:_,includes:x,lastModified:b,matches:I,name_i18n:M,name:h,namespace:y,options:o.options,position:w,resources:E,"run-at":D,supportURL:S,system:G,unwrap:A,updateURL:R,version:O,webRequest:L}),X=St({downloadMode:P,isFirstPartyIsolation:$,isIncognito:k,relaxedCsp:U,sandboxMode:F,script:q,scriptHandler:"Tampermonkey",
scriptMetaStr:o.header,scriptUpdateURL:V,scriptWillUpdate:!!V,userAgentData:j,version:N});n=X}return At(Dt(n))};return St({GM_info:St({get:o}),"GM.info":St({get:o})})})(),b=(()=>{const e=s(c.grant,Oo);let t=null;const n=(e,n)=>{const o=()=>{t==r&&(t=null),r=null};t&&t.disconnect();let r=t=to.connect("webRequest");return n&&r.onMessage.addListener((e=>{n(e.type,e.message||"ok",e.details)})),r.onDisconnect.addListener(o),r.postMessage(St({rules:e,uuid:c.uuid})),St({abort:()=>{r&&r.disconnect(),o()
}})};return St({GM_webRequest:e?St({value:n}):void 0,"GM.webRequest":e?St({get:()=>a(n)}):void 0})})(),M=(()=>{const e=s(c.grant,yo);let t=0;const n=St({}),o=(e,o,s)=>{if("string"!=typeof e)throw"invalid name";const a=++t,i=to.connect("registerMenuCommand"),{accessKey:l,autoClose:d,title:u}="string"==typeof s?St({accessKey:s}):s||St({});return i.onMessage.addListener((e=>{if("run"===e.method){const t=e.event,n=t?t.keyCode?new Un("keypress",t):new $n("click",e.event):void 0;Fo((()=>o(n)),1)}})),
i.onDisconnect.addListener((()=>{r(a)})),i.postMessage(St({method:"register",name:e,uuid:c.uuid,accessKey:l,autoClose:d,title:u})),n[a]=i.disconnect,a},r=e=>{let t;(t=n[e])&&(t(),delete n[e])};return St({GM_registerMenuCommand:e?St({value:o}):void 0,"GM.registerMenuCommand":e?St({get:()=>a(o)}):void 0,GM_unregisterMenuCommand:e?St({value:r}):void 0,"GM.unregisterMenuCommand":e?St({get:()=>a(r)}):void 0})})(),h=(()=>{const e=s(c.grant,po),t=(e,t)=>St({action:e,uuid:c.uuid,
location:zn.location.href,details:t}),n=St({set:(e,n)=>{o.first.send("cookie",t("set",e),n?e=>{n(e.error)}:null)},delete:(e,n)=>{o.first.send("cookie",t("delete",e),n?e=>{n(e.error)}:null)},list:(e,n)=>{o.first.send("cookie",t("list",e),n?e=>{n(e.cookies,e.error)}:null)}});return St({GM_cookie:e?St({get:()=>{const e=(e,t,o)=>(n[e]||(()=>{}))(t,o);return Xt(dt(n),(t=>{Gt(e,t,n[t])})),e}}):void 0,"GM.cookie":e?St({get:()=>{const e=St({});return Xt(dt(n),(t=>{
e[t]=e=>((e,t)=>new zn.Promise(((o,r)=>{if("list"==e){const s=t;n[e](s,((e,t)=>{t?r(t):o(e)}))}else if("set"==e){const s=t;n[e](s,(e=>{e?r(e):o(void 0)}))}else{const s=t;n[e](s,(e=>{e?r(e):o(void 0)}))}})))(t,e)})),e}}):void 0})})(),y=(()=>{const e=s(c.grant,vo),t=(e,t)=>"object"==typeof e?e:St({url:e,name:t,headers:void 0,saveAs:void 0,conflictAction:void 0,onprogress:void 0,onload:void 0,ondone:void 0,ontimeout:void 0,onerror:void 0}),n=(e,n)=>{const o=t(e,n),r=(e,t)=>{t=t||St({}),e&&Fo((()=>{
Et(e,t,[t])}),1)},{url:s,name:a,headers:i,saveAs:l,conflictAction:d}=o;let u=to.connect("download");u.onMessage.addListener((e=>{try{e.load?o.onload&&r(o.onload,e.data):e.progress?o.onprogress&&r(o.onprogress,e.data):e.timeout?o.ontimeout&&r(o.ontimeout,e.data):o.onerror&&r(o.onerror,e.data)}catch(e){Jn.log("env: Error: TM_download - ",e,o)}})),u.onDisconnect.addListener((()=>u=null));const p=St({details:St({url:s,name:a||"File.download",headers:i,conflictAction:d,saveAs:l}),uuid:c.uuid})
;return u.postMessage(p),St({abort:()=>{u&&u.postMessage(St({uuid:c.uuid,cancel:!0}))}})};return St({GM_download:e?St({value:n}):void 0,"GM.download":e?St({get:()=>(e,o)=>l(n,t(e,o))}):void 0})})(),w=(()=>{const e=s(c.grant,ho),t=(e,t)=>{let n,o,r=!1,s=null;const a=(()=>{const e=[];return St({run:t=>{if(t&&Vt(e,t),n)for(;e.length;)Ut(e)()}})})();let i=to.connect("openInTab");const l=()=>{i&&i.postMessage(St({close:!0}))};i.onMessage.addListener((e=>{e.tabId?r?l():(n=e.tabId,
a.run()):e.name?o=e.name:e.closed&&(r=!0,s&&(s(),s=null))})),i.onDisconnect.addListener((()=>i=null)),i.postMessage(St({method:"openTab",url:e,location:zn.location.href,options:t,uuid:c.uuid}));const d=St({});return gt(d,St({close:St({value:()=>{r?Jn.warn("env: attempt to close already closed tab!"):l()}}),focus:St({value:()=>{i&&i.postMessage(St({focus:!0}))}}),closed:St({get:()=>r}),onclose:St({get:()=>s,set:e=>{s=e}}),name:St({get:()=>o,set:e=>{a.run((()=>{i&&i.postMessage(St({name:e}))}))}})
})),d};return St({GM_openInTab:e?St({value:t}):void 0,"GM.openInTab":e?St({get:()=>a(t)}):void 0})})(),E=(()=>{const e=s(c.grant,So);return St({"window.close":e?St({value:e=>{o.first.send("closeTab",St({uuid:c.uuid}),e?()=>e():null)}}):void 0})})(),S=(()=>{const e=s(c.grant,Go);return St({"window.focus":e?St({value:e=>{o.first.send("focusTab",St({uuid:c.uuid}),e?()=>e():null)}}):void 0})})(),G=(()=>{const e=s(c.grant,bo),t=function(...e){Et(Jn.log,this,e)};return St({GM_log:e?St({value:t
}):void 0,"GM.log":e?St({get:()=>a(t)}):void 0})})(),R=({root:e,tag:t,properties:n,cb:r})=>{const s=Zn(),a=St({tag:t,properties:n,id:s,uuid:c.uuid});o.first.send("addElement",a,e,r?()=>r():null);const i=Xn.getElementById(s),l=n?n.id:void 0;return void 0!==l&&Sn(i,"id",l),i},O=(()=>{const e=s(c.grant,uo),t=(e,t)=>R(St({root:void 0,tag:"style",properties:St({textContent:e}),cb:t}));return St({GM_addStyle:e?St({value:t}):void 0,"GM.addStyle":e?St({get:()=>a(t)}):void 0})})(),L=(()=>{
const e=s(c.grant,uo),t=(e,t,n,o)=>{let r,s,a,i;return"string"==typeof e?(s=e,a=t,i=n):(r=e,s=t,a=n,i=o),a&&(a=St(a)),R(St({root:r,tag:s,properties:a,cb:i}))};return St({GM_addElement:e?St({value:t}):void 0,"GM.addElement":e?St({get:()=>a(t)}):void 0})})(),C=St({...L,...O,...E,...h,...y,...S,..._,...G,...M,...m,...w,...g,...d,...f,...p,...u,...b,...v});return r[e.script.uuid]=r[e.script.uuid]||C,r[e.script.uuid]}})},Bo=(e,t,n,o,r,s)=>{const a=(e,t,n,o,r)=>{const a=t[n],i=typeof a
;return o&&"string"===i?t[n]=()=>s(a,r):r&&"function"===i&&(t[n]=function(){return Et(a,r,arguments)}),Et(e,Wn,t)};let i=!0;eo((()=>i=!1));const l=St({}),c=e=>!!("object"==typeof e&&null!==e?e.capture:e),d=(e,o,r)=>{if("urlchange"!=e||!n["window.onurlchange"]){const n=c(r);let d,u;if(i&&((d="DOMContentLoaded"==e)||"load"==e)){const r=wn(Wn.document);if(d&&("complete"==r||"interactive"===r)&&"document-idle"!=t||!d&&"complete"==r)return void(async(e,t,n,o)=>{const r=St({attrName:"null",
newValue:"null",prevValue:"null",eventPhase:en,attrChange:Zt,target:Wn.document,relatedNode:Wn.document,srcElement:Wn.document});await null,n||await null,"load"===e&&await null,((e,t,n,o)=>{const r=St({attrChange:0,attrName:null,bubbles:!0,cancelBubble:!1,cancelable:!1,clipboardData:void 0,currentTarget:null,defaultPrevented:!1,eventPhase:0,newValue:null,prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:Dn()}),a="string"==typeof n?()=>s(n,o):n,i=new Event(e)
;Xt(dt(r),(e=>{Gt(i,e,r[e])})),Xt(dt(t),(e=>{Gt(i,e,t[e])})),Et(a,o,[i])})(e,r,t,o)})(e,o,n,g)}if("string"==typeof o||"object"==typeof r&&r.once)u=o;else{const t=`${e}-${n}`;l[t]=l[t]||[];const r=function(...e){return Et(o,this===Wn||this===Kn?g:this,e)};Vt(l[t],St({listener:o,filter:r})),u=r}return a(zn.addEventListener,[e,u,r],1,!0)}n["window.onurlchange"].value.register(o)},u=(e,t,o)=>{if("urlchange"!=e||!n["window.onurlchange"]){const n=c(o),r=`${e}-${n}`,s=l[r]&&$t(l[r],(e=>e.listener===t))
;if(s&&s.length){let t;if(Xt(s,(n=>{try{a(zn.removeEventListener,[e,n.filter,o],1,!0)}catch(n){t=n}const s=qt(l[r],n);l[r]=kt(l[r],s,1).result})),l[r].length||delete l[r],t)throw t;return}return a(zn.removeEventListener,[e,t,o],1,!0)}n["window.onurlchange"].value.unregister(t)},p=St({CDATA:St({value:function(e){this.src=e,this.toString=function(){return this.src},this.toXMLString=this.toString}}),uneval:St({value:e=>{try{return`\\$1 = ${Dt(e)};`}catch(e){Jn.log(e)}}}),define:St({value:void 0}),
module:St({value:void 0}),exports:St({value:void 0}),setTimeout:St({value:(...e)=>a(Vo,e,0,!0,g)}),setInterval:St({value:(...e)=>a(qo,e,0,!0,g)}),close:(()=>{const e=n["window.close"];return e?St({get:()=>Wn==Wn.top?t=>e.value(t):zn.close}):void 0})(),focus:(()=>{const e=n["window.focus"];return e?St({get:()=>t=>e.value(t)}):void 0})(),onurlchange:n["window.onurlchange"]?(()=>{let e=null;return St({get:()=>e,set:t=>{e&&u("urlchange",e),e=t,d("urlchange",e)}})})():void 0,location:St({set:e=>{
zn.location.href=e}}),name:St({get:()=>Wn.name,set:e=>{Wn.name=e}}),clearInterval:St({get:()=>No}),clearTimeout:St({get:()=>jo}),addEventListener:St({value:d}),removeEventListener:St({value:u}),console:St({get:()=>ro})});if(!e){const e=St({window:St({get:()=>g}),globalThis:St({get:()=>g}),cloneInto:St({value:e=>e}),exportFunction:St({value:(e,t,n)=>{const o=n&&Rt(n,"defineAs");return o&&(t[o]=e),e}}),createObjectIn:St({value:(e,t)=>{const n=St({}),o=t&&Rt(t,"defineAs");return o&&(e[o]=n),n}}),
undefined:St({get:()=>{}})});pt(p,e)}o&&pt(p,o);const g=r(p);return g};let Ho;(async()=>{const n=e.contextId;let o;const{fSend:r,fOnMessage:s,cloneInto:a,pageWindow:i}=e;o=r&&s?(({sendPrefix:e,listenPrefix:t,send:n,onMessage:o})=>{if(void 0===n||void 0===o)throw"invalid args";let r,s,a=1;const i=St({}),l=St({}),c=e=>{e&&(r=e)},d=e=>{const t=++a;return l[a]=e,t};o(((o,a)=>o==`${t}_${r}`?(t=>{const{m:o,r:a,a:c,n:d}=t;if(i[o]&&(Xt(i[o],(e=>e(c))),delete i[o]),"message.response"==o){
if(null==a)throw"Invalid Message";((e,t)=>{let n;e&&(n=l[e])&&(n(t),delete l[e])})(a,c)}else if(s){const t=a?t=>{n(`${e}_${r}`,St({m:"message.response",a:t,r:a}))}:()=>{};s(St({method:o,args:c,node:d}),t)}})(a):null));const u=St({init:async e=>{r?c():c(e)},refresh:()=>null,switchId:e=>{r&&u.cleanup(),c(e)},send:(t,o,s,a)=>Yn((i=>{let l,c;"function"!=typeof s&&null!==s?(l=s,c=a):c=s,n(`${e}_${r}`,St({m:t,a:o,r:c?d(c):null,n:l})),i()})),sendToId:(t,o,r)=>{n(`${e}_${t}`,St({m:o,a:r,r:null}))},
once:(e,t)=>{i[e]||(i[e]=[]),Vt(i[e],t)},setMessageListener:e=>{s=e},cleanup:()=>null});return u})(St({sendPrefix:"2U",listenPrefix:"2S",send:r,onMessage:s})):(({sendPrefix:e,listenPrefix:n,cloneInto:o})=>{const r=St({});let s,a,i=1;const l=St({});let c=!1,d=[];const u=()=>{m=Wn.document.documentElement,c=!1;const e=d;d=[],Xt(e,(e=>{c||b()?Vt(d,e):e()}))},p=e=>{const t=++i;return l[i]=e,t},g=(e,t)=>{const{m:n,a:r,r:s,n:a}=t,i=((e,t,n)=>{let r;var s;return n?(r=Qn("MutationEvent"),
Qt(r,e,!1,!1,n||null,void 0,void 0,Dt(t),Zt)):r=new kn(e,St({detail:(s=t,o?o(s,Wn.document):s)})),r})(e,St({m:n,a:r,r:s}),a);Et(Pe,Wn,[i])},f=t=>{const{m:n,r:o,a:i}=zt("CustomEvent"==Yt(c=t)?On(c):It(Gn(c)));var c;if(r[n]&&(Xt(r[n],(e=>e(i))),delete r[n]),"unlock"==n)g(`${e}_${a}`,St({m:"unlocked",a:void 0,r:null})),u();else if("unlocked"==n)u();else if("message.response"==n){if(null==o)throw"Invalid Message";((e,t)=>{let n;e&&(n=l[e])&&(n(t),delete l[e])})(o,i)}else if(s){const r=o?t=>{
g(`${e}_${a}`,St({m:"message.response",a:t,r:o}))}:()=>{};s(St({method:n,args:i,node:"MutationEvent"===Yt(t)?Rn(t):void 0}),r)}},v=e=>{e&&(a=e),a&&zn.addEventListener(`${n}_${a}`,f,!0)};let m,_;const b=()=>{if((()=>{const e=Wn.document.documentElement;return m||(m=e),m!==e})()){if(_){const e=_;_=void 0,e(Wn.document)}return!0}},M=St({init:async(n,o)=>{a?v():v(n),t&&!o&&await null,(m=Wn.document.documentElement,Yn((e=>{_=e;const t=new jn((()=>{b()&&t.disconnect()}));t.observe(Wn.document,St({
childList:!0}))}))).then((()=>{c=!0,M.refresh(),g(`${e}_${a}`,St({m:"unlock",a:void 0,r:null}))}))},refresh:()=>{const e=a;e&&(M.cleanup(),M.init(e,!0))},switchId:e=>{a&&M.cleanup(),v(e)},send:(t,n,o,r)=>Yn((s=>{let i,l;"function"!=typeof o&&null!==o?(i=o,l=r):l=o,b();const u=()=>{g(`${e}_${a}`,St({m:t,a:n,r:l?p(l):null,n:i})),s()};c?Vt(d,u):u()})),sendToId:(t,n,o)=>{g(`${e}_${t}`,St({m:n,a:o,r:null}))},setMessageListener:e=>{s=e},once:(e,t)=>{r[e]||(r[e]=[]),Vt(r[e],t)},cleanup:()=>{
a&&(zn.removeEventListener(`${n}_${a}`,f,!0),a=void 0)}});return M})(St({sendPrefix:"2C",listenPrefix:"2P"})),e.bridges.first=o;const l=pt(e.console,oo);o.init(n);const c=St({});o.setMessageListener((({method:t,args:n})=>{if("commid"==t)o.switchId(n.id),o.send("ack",St({id:n.id}));else if("injectable"==t)p(n.id,(()=>{o.send("ack",St({id:n.id}))})),o.send("injectableack",St({id:n.id}));else if("setForeignAttr"==t)Wn[n.attr]=n.value;else if("script"==t){
const{id:t,unwrap:r,bundle:s}=n,{script:a}=s,{name:i,uuid:l,options:{run_at:u}}=a;p(t,(t=>{const o=r?()=>t():()=>Et(t,((t,n,o,r)=>{const{pageWindow:s,cloneInto:a,exportFunction:i}=e,l=s||Wn,{script:c}=t,d=c.options.compat_powerful_this,u=-1!==qt(c.grant,"none");Ho=Ho||Xo(n);const p=Ho.of(t),g=e=>St({p:m,r:Et,s:e}),f=St({seed:St({get:()=>g(b),once:!0})}),v=St({}),m=St({GM:v}),_=l&&l;d&&(Gt(f,"GM",St({value:v})),Gt(f,"unsafeWindow",St({value:_}))),u||(m.unsafeWindow=_),Xt(dt(p),(e=>{
const t=gn(e,0,3),n=p[e];if(void 0!==n)if("GM_"===t)m[e]=void 0!==n.get?n.get():n.value,d&&Gt(f,e,n);else if("GM."===t){const t=Wt(e,3);ft(v,t,n)}}));const b=u?g(d?m:St({})):Bo(u,c.options.run_at,p,f,o,r);return b})(s,n.flags,d,g),[]);"document-start"==u||"context-menu"==u?o():c[l]=o})),o.send(`scriptack-${t}`,St({id:t}))}else if("port.message"==t)to.message(n,o);else if("external.connect"==t)(t=>{const{bridges:n}=e,o=Wn,r=Rt(o,"external");if(!r)return;const s=t?e=>t(e,o,St({cloneFunctions:!0
})):e=>e,a=(e,t)=>{n.first.send("external.message",e,t)};try{const e=()=>{const e=St({getVersion:e=>{a(St({method:"getVersion"}),(t=>e(s(t))))},openOptions:(e,t)=>{a(St({method:"openOptions",params:e}),t)},isInstalled:(e,t,n)=>{"function"==typeof t&&(n=t,t=null),a(St({method:"isInstalled",script:St({name:e,namespace:t})}),(e=>n(s(e))))}});return s(e)};gt(r,St({Tampermonkey:St({value:e(),configurable:!0})}))}catch(e){}})(a);else if("run"==t){const{uuid:e}=n,t=Rt(c,e);t?"function"==typeof t&&(t(),
delete c[e]):l.warn(`env: missing script "${e}"!`)}}));const{createProxy:d}=((e,t)=>{const n=(e=>{let t=St({});const n=(e,o,r)=>{const s=_t(e);s&&s===o||(null!=s&&--r>=0&&n(s,e,r),t=pt(t,bt(e)))};return n(e,null,5),t})(Wn);Xt(co,(e=>delete n[e]));const o=n;return St({createProxy:n=>{let r=o;const s=e=>{let t,n;const o=(t=mt(g,e))||(n=r[e]);return St({d:o?St(o):o,l:!!t,w:!!n})},a=e=>{if(!l(e))return!1;if("length"===e)return!0;const t=ht(Pn(e));return t>=0&&t<=nn&&e===`${t}`
},i=e=>"on"===gn(e,0,2),l=e=>"string"==typeof e,c=(e,n)=>{const o=gn(e,2),r=p[o];if(r&&(t.removeEventListener(o,r),delete p[o]),n&&(e=>"function"==typeof e)(n)){const e=(...e)=>Et(n,t,e);t.addEventListener(o,e),p[o]=e}},d=t=>void 0!==t&&(t===e||t===Wn||t===Kn),u=St({addEventListener:!0,alert:!0,atob:!0,blur:!0,btoa:!0,cancelAnimationFrame:!0,cancelIdleCallback:!0,captureEvents:!0,clearInterval:!0,clearTimeout:!0,close:!0,confirm:!0,createImageBitmap:!0,dispatchEvent:!0,dump:!0,fetch:!0,find:!0,
focus:!0,getComputedStyle:!0,getDefaultComputedStyle:!0,getSelection:!0,matchMedia:!0,moveBy:!0,moveTo:!0,open:!0,openDatabase:!0,postMessage:!0,print:!0,prompt:!0,queueMicrotask:!0,releaseEvents:!0,removeEventListener:!0,reportError:!0,requestAnimationFrame:!0,requestIdleCallback:!0,resizeBy:!0,resizeTo:!0,scroll:!0,scrollBy:!0,scrollByLines:!0,scrollByPages:!0,scrollTo:!0,setInterval:!0,setResizable:!0,setTimeout:!0,sizeToContent:!0,stop:!0,structuredClone:!0,updateCommands:!0,
webkitCancelAnimationFrame:!0,webkitRequestAnimationFrame:!0,webkitRequestFileSystem:!0,webkitResolveLocalFileSystemURL:!0});Xt(dt(u),(e=>{n[e]=n[e]||St({bind:!0})}));const p=St({}),g=St({});Gt(g,Mn,"Window");const f=new An(g,St({defineProperty:(e,t,o)=>{const{d:r,l:d}=s(t),u=St(o);return r&&!r.configurable&&(!!r.configurable!=!!u.configurable||!!r.enumerable!=!!r.enumerable)||a(t)?(ft(d?g:Wn,t,u),!1):(ft(g,t,u),l(t)&&i(t)&&c(t),delete n[t],!0)},deleteProperty:(e,t)=>{let{d:a,l:d,w:u}=s(t)
;return!(!a||!a.configurable)&&(d&&(d=delete g[t],l(t)&&i(t)&&c(t)),(u||(a=r[t])&&a.configurable)&&(o===r&&(r=pt(St({}),o)),u=delete r[t]),delete n[t],d||u)},get:(e,t)=>{const o=n[t];if(o){if(o.once&&delete n[t],"value"in o)return o.value;if(o.get)return o.get()}const{d:r,l:i}=a(t)?St({d:mt(Wn,t),l:!1}):s(t);if(r){let e;const n="value"in r?Rt(r,"value"):(e=Rt(r,"get"))&&"function"==typeof e?i?e():xt(e,Wn)():void 0;return n&&o&&o.bind?xt(n,Wn):i||"event"==t?n:d(n)||"globalThis"===t?f:n}},
getOwnPropertyDescriptor:(e,t)=>{let{d:o,l:r}=s(t);if(!o){const e=n[t];if(e)return St({enumerable:!0,configurable:!0,writable:!0,value:e.value,set:e.set,get:e.get});if(!a(t))return;o=mt(Wn,t),r=!1}const i=pt(St({}),o);if(d(i.value)&&(i.value=f),!r){const e=i.get;e&&(i.get=()=>{const t=xt(e,Wn)();return d(t)?f:t}),i&&!i.configurable&&ft(g,t,i)}return i},has:(e,t)=>t in g||t in n||t in r,ownKeys:()=>{const e=e=>!(e in r),t=dt(r),n=$t(dt(bt(g)),e),o=St({})
;for(let e=0;"Window"===Yt(Ot(Wn,e));e+=1)o[e]=!0;const s=$t(dt(o),e);return Nt(t,n,s)},preventExtensions:()=>!0,set:(e,t,o)=>{const r=n[t];if(r&&r.set)return r.set(o),!0;const{d}=s(t);return!(d&&!d.writable&&!Rt(d,"set")||a(t)||(delete n[t],Gt(g,t,o),l(t)&&i(t)&&c(t,o),0))}}));return f}})})(i,zn),u=e=>{o.send("csp",St({src:e}))},p=async(e,t)=>{ft(Kn,e,St({set:n=>{delete Kn[e];const o=yn(Wn.document);return o&&En(o),t(n)},configurable:!0,enumerable:!1})),eo((()=>delete Kn[e]))
},g=(e,t)=>t?((e,t)=>{const n=`__p__${Zn()}`;(async(e,t)=>{p(e,(e=>Et(e,t,[])))})(n,t),u('window["'+n+'"] = function(){'+e+"};"),delete Kn[n]})(e,t):u(e)})()})()};